### ISSUE TITLE
different backbones for maskrcnn not possible

### ISSUE THREAD

**Issue by chrbrgst** [airctic/icevision#1014]
I tried to use a resnet34 backbone for maskrcnn but however it seems it is not possible. I used the code from the notebook provided here: https://airctic.com/dev/getting_started_instance_segmentation/

I used to following code:

```
# create fastai learner
model_type = models.torchvision.mask_rcnn
backbone = model_type.backbones.resnet34

# some custom dataset
# [...]

model = model_type.model(backbone=backbone,
                                   num_classes=3)
learn = model_type.fastai.learner(dls=[train_dl, valid_dl],
                                       model=model,
                                       metrics=metrics)
```

Here is the traceback:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b591eb8a68e7> in <module>
      1 # create fastai learner
----> 2 model = model_type.model(backbone=backbone,
      3                                    num_classes=3)
      4 learn = model_type.fastai.learner(dls=[train_dl, valid_dl],
      5                                        model=model,

~...\lib\site-packages\icevision\models\torchvision\mask_rcnn\model.py in model(num_classes, backbone, remove_internal_transforms, **mask_rcnn_kwargs)
     51         resnet_fpn.patch_param_groups(model.backbone)
     52     else:
---> 53         model = MaskRCNN(backbone.backbone, num_classes=num_classes, **mask_rcnn_kwargs)
     54 
     55     patch_rcnn_param_groups(model=model)

AttributeError: 'TorchvisionBackboneConfig' object has no attribute 'backbone'

if I use the default backbone, it works correctly

**Comment by fstroth** [comment]
Hey @chrbrgst,

the backbone needs to be initialized.

```python
backbone = model_type.backbones.resnet34(pretrained=True)
```

If you want to train from scratch you can use `pretrained=False`. The notebooks are a bit outdated but we are currently working on bringing them uptodate.
