### ISSUE TITLE
FiftyOne integration

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#1016]
## 🚀 Feature

It would be great to integrate FiftyOne (FO) application with IceVision. It would be a bidirectional bridge:
- We can export predictions to FO, and leverage their features (similar images, hard examples, mistaken examples, etc.)
- We can import FO datasets (by creating an FO parser in IceVision)

FO also has an integration with OpenCV CVAT.

FO docs: https://voxel51.com/docs/fiftyone/tutorials/evaluate_detections.html

Finding mistakes (labels): https://voxel51.com/docs/fiftyone/tutorials/detection_mistakes.html

![image](https://user-images.githubusercontent.com/59614262/148411563-6673379d-5077-4269-891a-69dd9bc71c31.png)

**Comment by fstroth** [comment]
Closed with: https://github.com/airctic/icevision/pull/1031
