### ISSUE TITLE
Model predicts irrelevant images as correct prediction

### ISSUE THREAD

**Issue by thangaraj535** [airctic/icevision#1025]
I have trained with both fastai and pytorch model to predict bacterial disease in leaf. like below images
![download (7)](https://user-images.githubusercontent.com/74810897/149529085-ddd54c70-bf0b-4010-ac67-1291bc616ddd.png)
![download (13)](https://user-images.githubusercontent.com/74810897/149529098-9ee08bd0-798a-449f-b188-5bc75f7be482.png)

Also i have tested the trained model with some other irrelevant images, But it seems to be bug or some error while seeing the predicted images.
![download (10)](https://user-images.githubusercontent.com/74810897/149529455-10874a9b-f4bc-4dbd-bc0d-ee182696d819.png)
![download (9)](https://user-images.githubusercontent.com/74810897/149529460-2d22425b-cc72-4230-92af-35ac057668d1.png)
![download (8)](https://user-images.githubusercontent.com/74810897/149529462-41bc227b-eb7d-44cc-b739-8628fa196c41.png)
![download (15)](https://user-images.githubusercontent.com/74810897/149529465-6c8d8d8a-6122-4d6a-b53d-79851fc07390.png)
![download (14)](https://user-images.githubusercontent.com/74810897/149529469-fb186ca1-a0df-4048-a9e0-376f33108ab1.png)
![download (12)](https://user-images.githubusercontent.com/74810897/149529470-2db6df40-c1ff-4f83-945c-f9af4c333125.png)
![download (11)](https://user-images.githubusercontent.com/74810897/149529474-1266805a-e329-4f21-a86e-b64e5ec0d310.png)

**Comment by fstroth** [comment]
I think this is more of a training/generalization problem than a problem with the library. Can you give a short description of your dataset (num. imgs etc.)

**Comment by thangaraj535** [comment]
I have trained with 1008 images shown below. This is kind of predicting the specific disease that causes tomato crops leaf also in tomato. Please refer to the below images which were used for training.

Thanks for the instant reply and for being on top of resolving this issue...



![bacterial_spot (1004)](https://user-images.githubusercontent.com/74810897/149536134-416c1c7e-8ad7-4147-8fa6-0d7313707881.jpg)
![bacterial_spot (365)](https://user-images.githubusercontent.com/74810897/149536136-1f915ffe-d20e-4a67-ae21-fc0c690b8d84.jpg)
![bacterial_spot (383)](https://user-images.githubusercontent.com/74810897/149536141-96747cee-3ccb-4570-9499-eb2f3be72fac.jpg)
![bacterial_spot (400)](https://user-images.githubusercontent.com/74810897/149536142-36b564bd-e42e-428a-b72a-55ae87421dd8.jpg)
![bacterial_spot (485)](https://user-images.githubusercontent.com/74810897/149536143-e2221e68-47a9-48f3-90af-2181c317c555.jpg)
![bacterial_spot (486)](https://user-images.githubusercontent.com/74810897/149536144-86f858c6-163d-4fd9-ad1f-48cdc0c2138c.jpg)
![bacterial_spot (501)](https://user-images.githubusercontent.com/74810897/149536147-8f5d9922-ff21-4f3e-9a1b-78bc7b89eecb.jpg)
![bacterial_spot (630)](https://user-images.githubusercontent.com/74810897/149536149-ad98c049-8091-4731-8da7-03e621a473bd.jpg)
![bacterial_spot (740)](https://user-images.githubusercontent.com/74810897/149536151-ea429047-d100-4f24-ace3-a9837722fd3c.jpg)
![bacterial_spot (924)](https://user-images.githubusercontent.com/74810897/149536155-257ee590-a561-4edf-9a41-63e4663cf158.jpg)
![bacterial_spot (927)](https://user-images.githubusercontent.com/74810897/149536160-ec092c79-be24-4d48-b397-1b088a4ac602.jpg)
![bacterial_spot (933)](https://user-images.githubusercontent.com/74810897/149536167-9f628cf3-7ef5-46c1-9532-a230f639059b.jpg)
![bacterial_spot (948)](https://user-images.githubusercontent.com/74810897/149536169-035308e4-9e31-433a-a031-da2c11da49e0.jpg)
![bacterial_spot (966)](https://user-images.githubusercontent.com/74810897/149536171-283ace24-6de8-4cd1-a7e8-430ff20e48aa.jpg)
![bacterial_spot (972)](https://user-images.githubusercontent.com/74810897/149536172-e055a137-3e39-4a21-9f3f-dbb2ae5142d5.jpg)
![bacterial_spot (982)](https://user-images.githubusercontent.com/74810897/149536175-cae7d898-a974-40a3-b16e-f656856eecc2.jpg)
![bacterial_spot (989)](https://user-images.githubusercontent.com/74810897/149536179-1dd181bd-6b1f-4c7b-a6f6-6965e9017acf.jpg)

**Comment by fstroth** [comment]
The annotations are the whole objects?
For example here the annotation would be the tomato in the center:
![](https://user-images.githubusercontent.com/74810897/149536179-1dd181bd-6b1f-4c7b-a6f6-6965e9017acf.jpg)
 
If that is the case and most images above seem to be very similar with an object in the center and a plain background, then it could be that the NN learned to pick the center object that is distinguishable from the background.
Did you use negative sampling, this might help with the problem.

**Comment by thangaraj535** [comment]
Annotations did for the particular area of the image, may some of the annotations might be done as you mentioned. I did not use negative sampling and it would be very helpful if you can provide me some samples to do that.

**Comment by fstroth** [comment]
I will close the issue for now we can reopen the issue.

**Comment by thangaraj535** [comment]
I have tried as per the instruction you provided link in the above comment. But im facing this issue... do you have any idea to overcome this error.

![error](https://user-images.githubusercontent.com/74810897/149658971-baadfc51-3594-400c-b79e-9b4ac2a8a141.jpg)

**Comment by fstroth** [comment]
Do you use the pip version or master? On master, this should work thanks to a PR from potipot.

**Comment by thangaraj535** [comment]
I used this

!wget https://raw.githubusercontent.com/airctic/icevision/master/icevision_install.sh
!bash icevision_install.sh cuda11

**Comment by FraPochetti** [comment]
Try 
```
!wget https://raw.githubusercontent.com/airctic/icevision/master/icevision_install.sh
!bash icevision_install.sh cuda11 master
```

**Comment by thangaraj535** [comment]
Thank you so much for your help, can you please suggest to me how can I save the predicted image and print the bounding box coordinates of predicted classes?

**Comment by FraPochetti** [comment]
> print the bounding box coordinates of predicted classes

There are multiple ways to visualize predicted boxes. You can find those both in [this](https://airctic.com/dev/getting_started_object_detection/) and [this](https://airctic.com/dev/inference/) tutorial.

> save the predicted image

In the same cell in which you are running, say, `show_pred` or `show_preds` (see above tutorials for context) you can just add this line 
```python
plt.savefig("myimage.jpg")
```
where `plt` comes from `import matplotlib.pyplot as plt`

**Comment by thangaraj535** [comment]
I have used pip install icevision[all] command for installing the module but, while importing the library attributes it says "Module not found error" even i restarted the kernel as well.

**Comment by FraPochetti** [comment]
Can you please move this discussion to our [Discord](https://discord.gg/EQsUrTdU) server?

**Comment by balavenkatesh3322** [comment]
I'm getting below error,

```
  checkpoint_and_model = model_from_checkpoint(checkpoint_path,model_name="models.ross.efficientdet")
  File "/usr/local/lib/python3.7/site-packages/icevision/models/checkpoint.py", line 211, in model_from_checkpoint
    lib, mod = model_name.split(".")
ValueError: too many values to unpack (expected 2)
```
