### ISSUE TITLE
ConnectionError: Could not connect to `mongod`

### ISSUE THREAD

**Issue by Zubair2019** [airctic/icevision#1054]
## 🐛 Bug
**Describe the bug**
This behaviour happens when restarting the runtime in colab. Without a restart no connection error. It was working fine until 27th Jan 2021.

**To Reproduce**

**Expected behavior**
Shouldn't display this error.

**Screenshots**

**Desktop (please complete the following information):**
 - Colab VMware

**Additional context**

**Comment by dnth** [comment]
Hi @Zubair2019, is there a notebook you can share with us? I dont seem to face this issue.

**Comment by Zubair2019** [comment]
[https://colab.research.google.com/drive/16MHzyTPT_5TVteb4VmC3hCLdthMs1X35?usp=sharing](url)

**Comment by dnth** [comment]
I can't seem to open the Colab notebook. Can you please confirm if the link is correct?

**Comment by Zubair2019** [comment]
Hi, dnth
You can copy the link and paste into your browser. I have saved the cell outputs

**Comment by fstroth** [comment]
I started to look into the problem. There is something happening with fiftyone! 
If I install fiftyone normaly and import it all is fine but if I run the icevision install script afterwards there is an error.
Here is a notebook to reproduce the error: https://colab.research.google.com/drive/16MHzyTPT_5TVteb4VmC3hCLdthMs1X35?usp=sharing

**Comment by Zubair2019** [comment]
> I started to look into the problem. There is something happening with fiftyone! If I install fiftyone normaly and import it all is fine but if I run the icevision install script afterwards there is an error. Here is a notebook to reproduce the error: https://colab.research.google.com/drive/16MHzyTPT_5TVteb4VmC3hCLdthMs1X35?usp=sharing

Installing icevision and icedata via Pypi doesn't produce this error. Installing via the master does. But Pypi seems to install a few model than than the master

**Comment by FraPochetti** [comment]
We downgraded `fiftyone` (which was causing the issue) to a soft dependency.
It needs to be installed separately now.
Due to [this](https://github.com/airctic/icevision/pull/1055).
