### ISSUE TITLE
YOLOX __init__() got an unexpected keyword argument 'input_size'

### ISSUE THREAD

**Issue by JohnDuke259** [airctic/icevision#1062]
I trained a YOLOX model a couple weeks ago but when I load the checkpoint file for inference as follows:

```
checkpoint_path = 'models_meta/yolox_model_meta.pth'
checkpoint_and_model = model_from_checkpoint(checkpoint_path)
```

I get the following error:
```
load checkpoint from local path: models_meta/yolox_model_meta.pth

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     51     try:
---> 52         return obj_cls(**args)
     53     except Exception as e:

TypeError: __init__() got an unexpected keyword argument 'input_size'


During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)

7 frames

/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py in build_from_cfg(cfg, registry, default_args)
     53     except Exception as e:
     54         # Normal TypeError does not print class name.
---> 55         raise type(e)(f'{obj_cls.__name__}: {e}')
     56 
     57 

TypeError: YOLOX: __init__() got an unexpected keyword argument 'input_size'
```

This is how I saved my checkpoint:

```
save_icevision_checkpoint(modelyolox, 
                        model_name='mmdet.yolox', 
                        backbone_name='yolox_s_8x8',
                        classes =  parser1.class_map.get_classes(), 
                        img_size=image_size, 
                        filename=checkpoint_path,
                        meta={'icevision_version': '0.11.0'})
```

If I try to create and train a new model using the same code that worked before as follows:

```
model_type = models.mmdet.yolox
backbone = model_type.backbones.yolox_l_8x8
modelyolox = model_type.model(backbone=backbone(pretrained=True), num_classes=len(parser1.class_map), **extra_args) 
```

I get the same error.

I am using Google Colab.

I will be grateful if anyone can help me with this.

Thank you.

@FraPochetti  @potipot

**Comment by FraPochetti** [comment]
Maybe this is something our `mmdet` hero @dnth can look into? :)

**Comment by dnth** [comment]
Hi @JohnDuke259, we've been working to update the mmdet version in IceVision over the past few weeks and ran into few issues. This is one of them. 

A workaround you can try is to run `!pip install mmdet==2.20.0` in Colab, restart the notebook and see if the training works again. 

This, however, will cause the VFNet model to fail because of (I believe) a bug in mmdet implantation of VFNet. Hopefully, the bug gets fixed, and everything runs as usual again :)

Here is Colab notebook I ran
https://colab.research.google.com/gist/dnth/44113ea7a36957e717b1ffd35cc5f2d5/getting_started_object_detection.ipynb

**Comment by JohnDuke259** [comment]
Hi @dnth, thank you so much for your help! I really appreciate it. I will try the workaround you suggested.

**Comment by JohnDuke259** [comment]
I just tried your suggesting for inference and it worked. Thanks @dnth!

@FraPochetti  thanks for mentioning the `mmdet` hero! :)
