### ISSUE TITLE
Mobilene backbone for keypoint_rcnn model

### ISSUE THREAD

**Issue by fmobrj** [airctic/icevision#1066]
## 🐛 Bug
Trying to use mobilenet backbone in a keypoint_rcnn model is not working. Getting the following error:

> ValueError: Anchors should be Tuple[Tuple[int]] because each feature map could potentially have different sizes and aspect ratios. There needs to be a match between the number of feature maps passed and the number of sizes / aspect ratios specified.

```
model_type = models.torchvision.keypoint_rcnn
backbone = model_type.backbones.mobilenet()

model = model_type.model(backbone=backbone, num_keypoints=9) 

learn = model_type.fastai.learner(dls=[train_dl, valid_dl], model=model)

learn.lr_find()
```

The code works with resnet34_fpn and resnet18_fpn.

**Comment by FraPochetti** [comment]
`mobilenet` does not have a FPN component, hence the error.
We are working on polishing the backbones.
You should not be able to access the ones which are incompatible with the architecture.
To be clear, you can setup the FPN yourself on top of mobilenet but it's quite some work and I don't recommend it.

**Comment by FraPochetti** [comment]
Closing
