### ISSUE TITLE
keyerror with parser splitter

### ISSUE THREAD

**Issue by hoangkhoiLE** [airctic/icevision#1076]
## 🐛 Bug
**Describe the bug**
![image](https://user-images.githubusercontent.com/57557628/157046348-6a69a9e4-7890-4511-9187-7f02cec175bf.png)

Hello, I got an image and its annotation files in the directory but it continues to say "KeyError" ? Can any one tell me how to fix it ?

**Comment by FraPochetti** [comment]
what are `train_id` and `valid_id`?

**Comment by hoangkhoiLE** [comment]
It is the list of file name with out ".jpg". For example, ['7e1563e7e4ad167d',...]

**Comment by FraPochetti** [comment]
Does that image actually exist?

**Comment by hoangkhoiLE** [comment]
Sorry, I found the problem. Because there is error in the conversion of my file xml, so that the file xml contains another file name. So maybe it doesn't work !
