### ISSUE TITLE
How to retrieve predicted boxes  from a predicted image

### ISSUE THREAD

**Issue by GMSL1706** [airctic/icevision#1083]
Hello,

 I am working on license plate recognition and I would like to retrieve the boxes predicted by my model in order to be able to recognize the characters of the license plate as in [this example](https://medium.com/@quangnhatnguyenle/detect-and-recognize-vehicles-license-plate-with-machine-learning-and-python-part-3-recognize-be2eca1a9f12)

Can someone help me please ?

**Comment by fstroth** [comment]
Hey, currently we don't have an integration with any ocr system. You might want to take a look ![here](https://github.com/open-mmlab/mmocr) for ocr stuff.

**Comment by GMSL1706** [comment]
Ok. Thanks

**Comment by GMSL1706** [comment]
Sorry but I just want to make sure. Is there no way to save the predicted boxes as a list, integer or some other variable that we can use for other things?

**Comment by GMSL1706** [comment]
Can you show me how to do that ? Because I've tried but I didn't find the way to do that 

here is an example of my code
```
model = model_type.model(backbone=backbone(pretrained=True), num_classes=len(parser.class_map), **extra_args) 

# Selection = 0
state_dict = torch.load("./resnet50_fpn_mstrain_2x.pth")
model.load_state_dict(state_dict)

infer_dl = model_type.infer_dl(valid_ds, batch_size=4, shuffle=False)
preds = model_type.predict_from_dl(model, infer_dl, keep_images=True)

show_preds(preds=preds[3:4], show=True, display_label=True, figsize=(15, 20))
```
And Here is the output of prediction:

![téléchargement (2)](https://user-images.githubusercontent.com/85751497/161134664-2dc1d7b1-3149-4120-9992-53b07ac77ef8.png)

Which code could I use to save the predicted boxes please ?

**Comment by FraPochetti** [comment]
Here it is 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/1206519/161150361-1593c3c9-8a88-4b9e-90d7-b318d796a4e2.png">

**Comment by GMSL1706** [comment]
Thank you very much. That help me a lot. 

As I have the boxes data, I tried to use rectangle function of opencv lib as [here](https://www.geeksforgeeks.org/python-opencv-cv2-rectangle-method/) on the same image. But I realize that I have to use the predicted image because there was some processing on the original data (I suspect that the boxes data are for processed images) and it is difficult for me to work with the original image.

Is there any function that can help to save the predicted image with `preds[0]` as you did with the boxes data please ?

**Comment by FraPochetti** [comment]
Check out `end2end_detect` inside the inference [tutotial](https://airctic.com/0.12.0/inference/) for what you are asking

**Comment by GMSL1706** [comment]
THANK YOU VERY MUCH !!!!!!!!!!!! I AM VERRY HAPPY
