### ISSUE TITLE
YoloV5 - rectangular images clarification

### ISSUE THREAD

**Issue by kuntiik** [airctic/icevision#1092]
Hello, 
currently yolov5 model is not supporting rectangular images, even though the original ultralytics repo does that. How hard is modifying the code to support that? Will you consider adding this feature? 
Regards

**Comment by fstroth** [comment]
You can use padding to get the desired shape. But I don't think we will add that feature, at least not any time soon.

**Comment by kuntiik** [comment]
My bad I went thru the ultralytics repo and found that I am able to train on rectangular images. I am not 100% sure, but it seems, that you only specify the longer side of the image. Right now I have rectangular images (960*768) and I passed 960 to the yolov5 model and it works...
But I would really appreciate any clarification from someone who understands it more than I do.

**Comment by FraPochetti** [comment]
As @fstroth said, we don't have the bandwidth to add rectangular-images training, but, again confirming what Frederik suggested, padding is more than sufficient. It will guarantee you don't change the image aspect ratio, hence basically allowing you to train on rectangular images.

**Comment by kuntiik** [comment]
Thank you for the answer, 
what remains unclear is this: I resize my images to a rectangular shape and set the image size of the YOLOv5 model to the longer side of that rectangle. When I start training it works...
The question is why? I would expect the program to crash because it expects a square image.
