### ISSUE TITLE
Docker credentials warning

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#113]
## 🐛 Bug
Currently the docker action is giving the following warning:
```
WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
```

It's not so clear if that is a flaw or not, but from [this](https://github.com/actions/starter-workflows/issues/96) issue it seems that the best solution would be to use the [official docker action](https://github.com/marketplace/actions/build-and-push-docker-images)

@oke-aditya can you check this one?

**Comment by lgvaz** [comment]
Btw, for checking a custom branch in the action, you should use:
```
- uses: actions/checkout@v2
  with:
    ref: my-branch
```

Take a look [here](https://github.com/actions/checkout) for more info

**Comment by oke-aditya** [comment]
This is issue is open with Docker official action as well. They are looking into it.
Have a look here.

https://github.com/docker/build-push-action/issues/53

I hope they will fix it soon.

**Comment by oke-aditya** [comment]
As of now the best thing is to use the official docker action. And Keep this issue opened. One docker officially resolves it and we verify. We can close it.
