### ISSUE TITLE
Cannot get deterministic order for records

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#147]
## 🐛 Bug
**Describe the bug**
Even when using the same seed on `RandomSplitter` we are unable to get the same `train/valid` split, and even the order of the records inside each set changes.

**To Reproduce**
Run the following on two different colab notebooks and get different results:
```python
data_dir = datasets.pets.load()
parser = datasets.pets.parser(data_dir)
data_splitter = RandomSplitter([.8, .2], seed=42)
train_records, valid_records = parser.parse(data_splitter)
show_record(train_records[0])
```

**Expected behavior**
Have the same image on both notebooks.

**Comment by lgvaz** [comment]
I think this happens because `get_image_files` does (that is called inside the parser constructor) not guarantee that the order of the images is always the same.

**Comment by oke-aditya** [comment]
To deterministically cut a folder into two halves we can do this.

```
shuffled_list = random.shuffle(os.listdir(image_folder), seed=seed)
train = shuffled_list[:len(shuffled_list) * fraction_train]
test = shuffled_list[len(shuffled_list) * fraction_train :]
``` 

And then read the images in the two splits using PIL or open-cv (faster). This would keep it deterministic I guess.

**Comment by lgvaz** [comment]
The problem is not on the splits, but on the `os.listdir` itself, or more specifically, in the function `get_image_files`.

If you run the piece of code on your computer twice you are going to get the same results. But, they are not going to be the same when I run on my computer, and that's the problem

**Comment by oke-aditya** [comment]
I get the point. in `get_image_files` we are using `os.walk()` which internally uses `os.listdir()`. I guess to solve this we can refer [here](https://stackoverflow.com/questions/18282370/in-what-order-does-os-walk-iterates-iterate). We need to sort (extra overhead) and then use `random.shuffle`.

```
for rootName, dirNames, fileNames in sorted(os.walk(path)):
    #root, dirs and files are iterated in order...
```

Then shuffle deterministically for the list of names.

**Comment by lgvaz** [comment]
You're correct, somehow we have to sort it

Maybe we can do that inside `Parser.parse_dicted`, after the first for loop. We can try sorting and returning a `OrderedDict`.. That's is just my first thought, maybe we can refactor the method a bit so it's more natural.

**Comment by lgvaz** [comment]
Partially fixed by #203, sorting the files in `get_files`, but the problem is actually in `Parser.parse_dicted` where we are using a dictionary and `CombinedParser` where we are using a set.

We could use an `OrderedDict` and some kind of ordered set respectevily.

Or we can always sort by ID after the operations are done.

**Comment by lgvaz** [comment]
I think this should be solved, we just need to run some experiments and write tests to be sure

**Comment by FraPochetti** [comment]
Not relevant anymore
