### ISSUE TITLE
Dash App Presentation

### ISSUE THREAD

**Issue by oke-aditya** [airctic/icevision#172]
## 🚀 Feature

An example of how to use mantisshrimp with Dash.

I guess you are on it @paras-jain. Just keeping this issue open so that you text here if help is needed.

Also you can close this issue by adding the Dash Example to Readme / docs.

**Comment by paras-jain** [comment]
Will update regarding the dash app here.

**Comment by lgvaz** [comment]
Hey @paras-jain, are you still working on that or can I close this?

**Comment by paras-jain** [comment]
It was complete, will have to tweak a little to incorporate new changes. Same for gradio, feel free to close this.

**Comment by lgvaz** [comment]
Cool! Before I close this, can you share a link to the project?
