### ISSUE TITLE
Mantisshrimp TPU Training

### ISSUE THREAD

**Issue by oke-aditya** [airctic/icevision#185]
## 🚀 Feature

TPU training of models with mantisshrimp. It would be great to have, faster convergence and better training.
Also, it eliminates the boilerplate and pain required for end-user to transfer the GPU object detection models to TPU using xm.

We have PyTorch Lightning engine which natively supports TPU training through torch_xla.
I am unsure with Fastai2 if it supports TPU training. 
I tried training Faster RCNN using TPU. It throws an error because of some torchvision native operations are not supported over TPU. Example [code](https://colab.research.google.com/drive/1w-75fFsV0rxjFQnag_jWIhIHU__U-qjJ?usp=sharing)

I have also opened an [issue ](https://github.com/pytorch/vision/issues/2486) with torchvision team, let us see what they answer.

**Comment by ai-fast-track** [comment]
Fastai doen't support TPU

**Comment by oke-aditya** [comment]
Any future Plans to support TPU by Fastai or fastai v2. Lightning has TPU tests too, so their package is even tested on TPU.
