### ISSUE TITLE
Add a new section in Docs about Models

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#245]
FasterRCNN, and EfficientDet models. For each model, we should have:

* A short description of the model
* Link to the original paper, and some interesting blogs
* Some illustrations
* Some code snippets with links to Colab NBs

---
@oke-aditya , @paras-jain , would you be interested in working on this?

**Comment by oke-aditya** [comment]
👍 will do it.

**Comment by oke-aditya** [comment]
@ai-fast-track how should this be. Should I simply write a `.md` file about each of them, containing code examples and description ?

**Comment by lgvaz** [comment]
It would be nice to have a docstring description on top of the `model.py` file that could be automatically parsed to show on the API documentation itself. Between `Faster RCNN` and `model` in the following image:

![image](https://user-images.githubusercontent.com/16520544/89073232-714df400-d350-11ea-8d9d-80a3a1b249d9.png)

I tried some experiments with that but failed. Another alternative would be to add that description in the `model` docstring itself
