### ISSUE TITLE
Readme "not include in docs" tags bug

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#250]
## 🐛 Bug
It's possible to hide certain portions of the readme so they are not showed in the docs. This can be done with the tags:

```
"<!-- Not included in docs - start -->"
"<!-- Not included in docs - end -->"
```

The tags are parsed under `autogen.py`:
```python
    start = readme.find("<!-- Not included in docs - start -->")
    end = readme.find("<!-- Not included in docs - end -->")
    print("\nSTART: ", start)
    print("END: ", end, "\n")
    readme = readme.replace(readme[start:end], "")
```

This works well when we want to hide a single continuous block of text, but will fail for multiple sections.

Instead, we need to **find all** tags, iterate over then and remove their corresponded sections.

---
**Bonus:** The above only works in the readme (which is fine for now), but it would be nice to extend this functionallity to work with any md file.

**Comment by FraPochetti** [comment]
Not relevant anymore
