### ISSUE TITLE
Greet a new contributor

### ISSUE THREAD

**Issue by oke-aditya** [airctic/icevision#251]
## 🚀 Feature

Nothing great regarding to the repo.
We can simply greet a new user who is trying to make his first PR / issues.

This can be done using `greetings.yml` file in the workflows.

**Comment by lgvaz** [comment]
There are greeting bots available in the marketplace right?

**Comment by oke-aditya** [comment]
I will explore the options on marketplace. And let you know. Greetings.yml is simplest though.

**Comment by lgvaz** [comment]
The bots will be a single click to deploy =)

And they will have a pool of messages

**Comment by oke-aditya** [comment]
This is a nice bot [welcome](https://github.com/apps/welcome).
They aren't NLP powered yet, but we can at least write a nice message.
