### ISSUE TITLE
Keras-autodoc and dataclass

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#264]
## 🐛 Bug
**Describe the bug**
It seems keras-autodoc has a problem parsing a `dataclass` like `BBox`, the following error occur when running `autogen.py`:

```python
  File "/Users/lgvaz/anaconda3/envs/mantis/lib/python3.7/site-packages/keras_autodoc/utils.py", line 73, in get_class_from_method
    meth.__qualname__.split('.<locals>', 1)[0].rsplit('.', 1)[0])
AttributeError: module 'mantisshrimp.core.bbox' has no attribute '__create_fn__'
```

Removing `@dataclass` from `BBox` fixes the issue.

I see two solutions here:

## Solution 1
Fork keras autodoc and fix the issue (it should be relatively simple), we can make a PR to the original repo and keep use the fork until they merge it.

## Solution 2
Stop using `dataclass`. Kind of a radical solution, dataclasses offer us some nice benefits... But if we fail to fix it, we can just use normal classes

**Comment by ai-fast-track** [comment]
@lgvaz, I would go with Solution 1, take from there. By filing a PR, we are also giving back to the keras_autodoc team who built a very useful package.

**Comment by FraPochetti** [comment]
@ai-fast-track is this one still relevant or can we close?

**Comment by FraPochetti** [comment]
@ai-fast-track wdyt?
