### ISSUE TITLE
Pycocotools alternative

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#283]
Pycocotools is causing a lot of problems. It's currently mainly used for calculating metrics, it would be nice to find an alternative.

[This](https://github.com/rafaelpadilla/Object-Detection-Metrics) is a strong alternative. Please comment if you have a candidate =)

**Comment by oke-aditya** [comment]
I have seen this. It is a good alternative but still lacks an API. See the readme for usage, there is no way we can actually compute metrics and add them.

Best alternatives against PyCoco are, lightning metrics, raise a feature request for metrics package in torch. They had this request before too.

**Comment by lgvaz** [comment]
pycocotools is currently also being used on `Polygon.to_mask`, we also need to find an alternative way of doing that.

**Comment by lgvaz** [comment]
Because of #510 masks are now heavily dependent on pycocotools because of the heavy use of "Encoded RLE"

**Comment by FraPochetti** [comment]
We don't have any bandwidth to think about removing this dependency for the time being
