### ISSUE TITLE
Clarify samples and records

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#349]
Currently, in the library, it's very confusing what are `records` and what are `samples`.

A record is what we get immediately after parsing the data.
A sample is what we get out of a `Dataset`.  

Additional confusion can come from the fact that both satisfies `RecordType`, which simply is: `RecordType = Dict[str, Any]`

The differences are subtle but very important. A record normally only have the file path to an image, while a sample holds the image (np.array) in memory.

Some functions like `faster_rcnn.build_train_batch` have the **wrongly** named parameter `records` instead of `samples`, but passing a `record` to this function will simply fail because this expects the image to already be opened.

 We need to rename all of those occurrences.

**Comment by lgvaz** [comment]
This naming convention error is also shown in the API documentation. In the example use case given for those function.

**Comment by FraPochetti** [comment]
Not relevant anymore
