### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#355]
## 🐛 Bug
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]

**Additional context**

**Comment by lgvaz** [comment]
Yeah, we got our feet wet with docker but eventually faced some problems and decided to leave it on the side for a while.

I honestly don't understand docker too much, @adamfarquhar would this be something you would be interested in helping us out? 😄

**Comment by oke-aditya** [comment]
Yeah the Dockerfile needs and update. @lgvaz I guess we need to fix this NVIDIA Docker stuff before next release. We will fix both docker deployment action and these container builds as well.

**Comment by adamfarquhar** [comment]
I think that it is important not to include stuff that is known to be broken in the main branch. Especially something like Docker, which people will use as a quick way to try the system out. I may be able to help with this, but perhaps after the dust settles from the renaming (i.e., later in September). @oke-aditya - if you have strong Docker skills, though, it would be great if you had the chance.

**Comment by oke-aditya** [comment]
Yes I can @adamfarquhar . But I am a bit busy this and next week. I will fix it up. We will also have CI to deploy in over Docker cotainer registry.

**Comment by lgvaz** [comment]
Did any of you had progress with this? We're now in a very good stage to add docker support but sincerely I don't have the required docker skill to do so :sweat_smile:

**Comment by oke-aditya** [comment]
Docker on my PC is broken 😢  But If we use a CI it will build over GitHub.

**Comment by ydcjeff** [comment]
@lgvaz can I take this over? If yes, what would you like to install in Dockerfile?

**Comment by lgvaz** [comment]
Hi @ydcjeff! Thanks for reaching out! I'll assign this issue to you =)

> what would you like to install in Dockerfile?

We just need to install icevision and icedata with GPU support, I'm thinking the best would be to have a local/editable installation of both?

Hm.. There are actually two situations:
- Developer installation: install in editable mode with the flags `pip install ".[all,dev]"`
- User install: install from pypi?

Any suggestions you have in mind?

**Comment by ydcjeff** [comment]
If you want the docker to be used to by the users, user install is good to go.

**Comment by lgvaz** [comment]
Is there an easy way to have both? Maybe with tags we can have `dev`?

**Comment by ydcjeff** [comment]
If you want both, I think maybe two separate environments should work.

**Comment by lgvaz** [comment]
Cool! Can we start with that and see how it looks?

@adamfarquhar let me tag you here, do you like the idea of having two envs?

**Comment by ydcjeff** [comment]
So, shall I draft a PR?

**Comment by lgvaz** [comment]
> So, shall I draft a PR?

yeah! and we can keep building on that

**Comment by FraPochetti** [comment]
Not relevant anymore
