### ISSUE TITLE
fastai warning - setting an attribute (loss) that also exists in the learner

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#356]
## 🐛 Bug
**Describe the bug**
/opt/conda/lib/python3.7/site-packages/fastai2/callback/core.py:50: UserWarning: You are setting an attribute (loss) that also exists in the learner, so you're not setting it in the learner but in the callback. Use `self.learn.loss` otherwise.
  warn(f"You are setting an attribute ({name}) that also exists in the learner, so you're not setting it in the learner but in the callback. Use `self.learn.{name}` otherwise.")

**To Reproduce**
1. Happens on a fresh build of Mantisshrimp and call to:
learn = faster_rcnn.fastai.learner(dls=[train_dl, valid_dl], model=model, metrics=metrics)

**Comment by lgvaz** [comment]
Yeah, although this warning can be annoying it's not a bug.

I know where this is coming from, I'll see if I can re-arrange things to stop this warning.

**Comment by adamfarquhar** [comment]
Thanks. This is the sort of thing that is disconcerting to the user. So, while not necessarily a bug, it causes doubt as to whether the underlying system is doing the right thing.

**Comment by lgvaz** [comment]
Can be related to #434. Need to check this again after updating the fastai version.

**Comment by FraPochetti** [comment]
Not relevant anymore
