### ISSUE TITLE
defaultinfoparser

### ISSUE THREAD

**Issue by arhamzamindar** [airctic/icevision#359]
## 🐛 Bug
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 18.04]

**Additional context**

**Comment by arhamzamindar** [comment]
NameError: name 'DefaultImageInfoParser' is not defined

**Comment by lgvaz** [comment]
Hello, as explained in #353:

`DefaultImageInfo` is going to be deprecated, use the smaller building blocks instead:

```python
class ResumeParser(parsers.FilepathMixin, parsers.SizeMixin, parsers.FasterRCNN):
```

Is `DefaultImageInfoParser` being used in a tutorial? Let me know and I'll update that

**Comment by arhamzamindar** [comment]
thanks @lgvaz  for your quick response. Another issue i am facing is 

NameError: name 'Path' is not defined

this is the error i am receiving now when defining my dataset directory.

**Comment by arhamzamindar** [comment]
thanks for your help the error is solved by there's a problem again 
AttributeError: 'Pandas' object has no attribute 'image_id'

this is the error i am getting now when running the below code
data_splitter = RandomSplitter([.8, .2])
parser = ResumeParser(df1, source / "train")
train_rs, valid_rs = parser.parse(data_splitter)

**Comment by arhamzamindar** [comment]
from mantisshrimp.models.mantis_rcnn import * running this now i get the below error
ModuleNotFoundError: No module named 'mantisshrimp.models.mantis_rcnn'

I can create and load the dataset but cant train on it .

**Comment by lgvaz** [comment]
Because of the activity on #365 I believe this is fixed.
