### ISSUE TITLE
Polygon.to_mask includes an assert that may not be needed

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#383]
## 🐛 Bug

**Describe the bug**
Polygon.to_mask has an assert in case it thinks that polygons overlap. This was triggered by my data, even though I wasn't needing to use the segmentation information/masks. It should't trigger an unrecoverable error in such a case.

**Additional context**
A simple fix:
```
def patch_to_mask(self, h, w):
        erle = self.to_erle(h=h, w=w)
        mask = mask_utils.decode(erle).sum(axis=-1)  # Sum is for unconnected polygons
        # assert mask.max() == 1, "Probable overlap in polygons"
        if mask.max() == 1: 
            print("Probable overlap in polygons")
        return MaskArray(mask)
Polygon.to_mask = patch_to_mask
```

**Comment by lgvaz** [comment]
I'll be investigating this further, but I believe this assertion might be essential while training a segmentation model.

After all the model expects binary masks, the assert makes sure the mask only has 0's and 1's.

I believe you're using the coco parser? If so, and you want to train a model without segmentation masks, use the option `mask=False`

**Comment by lgvaz** [comment]
With #510 the way `Polygon` gets converted to masks changed so the assert is not there anymore
