### ISSUE TITLE
Tutorials and Examples

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#39]
## 📒 Tutorials
Tutorials are in `.ipynb` format, explaining each step of the process, really detailed, not production like.

**Core**
- [x] [parser](https://lgvaz.github.io/mantisshrimp/tutorials/parser.html)

**Object detection**
- [x] [wheat](https://lgvaz.github.io/mantisshrimp/tutorials/wheat.html)
- [x] [wheat with detr](https://lgvaz.github.io/mantisshrimp/tutorials/hub_detr_finetune_wheat.html)

**Segmentation**
- [ ] [penfundan](https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html)

**Keypoints**

## 📓 Examples
Examples are be in the `.py` format, more production oriented. Ready to be run with arguments from the command line and easy to integrate with wandb sweeps and alike.

**Object detection**
- [ ] [wheat](https://www.kaggle.com/c/global-wheat-detection)

**Segmentation**

**Keypoints**

---
Is there a new tutorial or example you would like to add? Comment below and we talk about it 😁

Once we agree, create an **Tutorial or Example request** issue (use the template) and I'll edit this post with your new cool example!

**Comment by lgvaz** [comment]
It would be a cool addition to show how to do a wandb sweep in the whet example

**Comment by chho-work** [comment]
Certainly it would be, Wandb supports Pytorch Lightning: https://docs.wandb.com/library/frameworks/pytorch/lightning

I will work on few examples with different datasets!

**Comment by lgvaz** [comment]
It might be a good idea to separate this into `Examples` and `Tutorials`.

Tutorials would be in `.ipynb` format, explaining each step of the process, really detailed, not production like.

Examples would be in the `.py` format, more production oriented. Ready to be run with arguments from the command line and easy to integrate with wandb sweeps and alike.

What do you think @chho-work ?

**Comment by chho-work** [comment]
Yes, it would be great to have both available, examples and tutorials, each with their corresponding formats.

**Comment by chho-work** [comment]
I found this pretty interesting!  I think we can use them in tutorials and examples.
https://github.com/mseg-dataset/mseg-api

**Comment by tazu786** [comment]
Hi, sorry for my probably silly question, but when I run 
>run_detr(args, train_dataset, valid_dataset)

in the tutorial for fine tuning the detr, I get
> TypeError: main() takes 1 positional argument but 3 were given

How can I pass the datasets to the main(args) of detr?

Thank you

**Comment by tazu786** [comment]
Hi, I have question regarding the new [colab ](https://colab.research.google.com/github/lgvaz/mantisshrimp/blob/master/tutorials/hub_detr_finetune_pennfundan.ipynb)on detr fine tuning. Right after loading the checkpoint with no head, shouldn't I freeze all the other layers with something like: 
>    for param in model_without_ddp.parameters():
        param.requires_grad = False
    model.class_embed.weight.requires_grad = True
    model.class_embed.bias.requires_grad = True

Thanks

**Comment by lgvaz** [comment]
That's something we could do as well correct, we actually have an issue for that in #72

**Comment by lgvaz** [comment]
We should change the definitions of tutorials and examples.

Tutorials should be non-repetitive, and should all show in the documentation. Having too many tutorials might confuse beginners! Tutorials should be maintained and created by the core team.

Examples should be a mix of core/community, the can be scripts or notebooks and don't need to explain library concepts. There is no limit to the number of examples we should have, the more the better!

Examples also go very well together with datasets implementations in `hub`. Maybe all examples should actually be all inside `hub`? This would make them always self-contained (all functions for downloading data, creating parsers, etc would be present)

@ai-fast-track what do you think?

**Comment by ruffson** [comment]
I don't know if this is the best place to ask this, but I find it quite confusing that the [getting started](https://airctic.com/0.7.0/getting_started_object_detection/#install-icevision-and-icedata) tutorial instructs the user to install everything "by hand" with a shell script which is not what you ussually want to do. 

So when I installed everything properly and cleanly in a conda env via the [install page](https://airctic.com/0.7.0/install/) I came back to do the getting started tutorial but then was missing `IceData`.

I think it is nice to have a page that just enables you to install and run everything to test things out. But on the other hand there should also be a path to follow a getting started guide right after installing everything completely.


So IMO the object detection needs to refer to the installation instructions (like the [image segmentation](https://airctic.com/0.7.0/getting_started_instance_segmentation/) does already). And additionally the installation instructions need contain instructions to install icedata.

**Comment by lgvaz** [comment]
> So IMO the object detection needs to refer to the installation instructions (like the image segmentation does already). And additionally the installation instructions need to contain instructions to install icedata.

Totally agree on both points! We should do that

@ruffson Would you like to make the changes and submit a PR?

**Comment by ruffson** [comment]
> > So IMO the object detection needs to refer to the installation instructions (like the image segmentation does already). And additionally the installation instructions need to contain instructions to install icedata.
> 
> 
> 
> Totally agree on both points! We should do that
> 
> 
> 
> @ruffson Would you like to make the changes and submit a PR?

Sure, I'll do that!
