### ISSUE TITLE
Custom domain name (CNAME) is reset each time docs are generated

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#391]
## 📓 Documentation Update
**What part of documentation was unclear or wrong?**
Whenevery a PR is merged, docs are automatically re-generated, and the custom domain name (CNAME file) is reset to an empty string. Therefore, the documentation website cannot be reached

**Describe the solution you'd like**
**Temporary Solution:** Set the custom domain name to **airtic.com** in the Setting** page after each PR merge. 

We should test the option of creating a permanent CNAME file in docs with **airctic.com** in it.

**Comment by oke-aditya** [comment]
Yeah it's very simple, just make a CNAME file in root of repo.

**Comment by ai-fast-track** [comment]
Closed: Fixed in the PR #399
