### ISSUE TITLE
How to contribute guide references requirements.txt, which is not in the repo

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#393]
## 📓 Documentation Update
The [contributing guide](https://airctic.com/contributing/) has an 'install requirements' step that references `requirements.txt`, but there is no `requirements.txt` at the top level of the repo.

**Comment by oke-aditya** [comment]
The `requirement.txt`is not needed, they are mentioned in `settings.ini` file. I remebering cleaning this.

**Comment by lgvaz** [comment]
Yeah, that's the thing, we removed the usage of it but forgot to clean the documentation

**Comment by ai-fast-track** [comment]
Implemented in the PR #403
