### ISSUE TITLE
NameError: name 'efficientdet' is not defined

### ISSUE THREAD

**Issue by SilasGG0530** [airctic/icevision#398]
Hi there,

Sorry if my post is strange, this is the first attempt at submitting an issue with GitHub.

I'm trying to follow the VOC dataset tutorial step-by-step and everything worked fine yesterday. However today I get stick on any step involving efficientdet getting this error

![image](https://user-images.githubusercontent.com/69086014/92716024-f0c6de00-f366-11ea-9c33-61975c1f9c5b.png)

Tried it both with Colab and Jupyter, same issue. I have even tried running the exact example with the raccoon dataset - same issue.
Any help would be appreciated

**Comment by lgvaz** [comment]
Hello @SilasGG0530, hope you doing well

First of all, your post does not seem strange, this is exactly what issues are for =)

The issue you're facing is a bug on our part, we're making changes on how to package the library, and efficientdet is not installed automatically anymore, our tutorial notebooks need to be updated.

To fix the issue, install effdet with the following before running the imports.
```bash
pip install omegaconf effdet@https://github.com/rwightman/efficientdet-pytorch/archive/master.zip#egg=effdet-0.1.4
```

**Comment by lgvaz** [comment]
I just updated the installation in the tutorials, it should work now

Thanks for pointing out!

**Comment by sebderhy** [comment]
The same error happens to me now on my notebook after I upgraded to the latest version. 

Strangely, I do not manage to reproduce the error on the colab (but it was definitely working on the previous versions). 

Thanks
