### ISSUE TITLE
Add a step to apply `black` formatting before pushing commits

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#410]
## 📓 Documentation Update
**What part of documentation was unclear or wrong?**
Lacking to apply black before a merging leads to CI failing.

**Solution**
Add a extra step at before pushing commits explaining how to apply black for code formatting

**Comment by lgvaz** [comment]
Also, there are these things called "pre-commit hooks" that can automatically run black whenever you commit.

I'm not sure how it works, more info can be found [here](https://black.readthedocs.io/en/stable/version_control_integration.html)
