### ISSUE TITLE
Coco class_map

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#414]
### The problem
As pointed out by @adamfarquhar, when handling COCO style annotations the annotation file ended up being loaded twice, once to create the `ClassMap` and the other to parse the data.

This can especially be a problem if the annotation file is big and takes long to read.

### Solution 1
It's possible to also return the class_map when creating the parser:

```python
parser, class_map = parsers.coco(...)
```

**Question:** Can we assume that the annotations will **always** have the classes section?

**Drawback:** This would be inconsistent with the VOC parser, there the classes are not stored in the annotation file and it has to be manually defined by the user.

### Solution 2
A solution proposed by @adamfarquhar was to store the `ClassMap` as an attribute of the `Parser`.

The immediate issue here is that not all parsers require a `ClassMap`, this would lead to inconsistencies between datasets. Forcing all parsers to store the classmap would limit the flexibility of the API.

The only reason some parsers need a class_map (e.g. VOC) is because the labels in the annotation files are stored as names (e.g. chair) instead of indexes (e.g. 12).

In the COCO scenario, the labels are already the indexes, so the class_map is only "required" when showing the data (only if you want to replace the indexes with class names).

**Comment by adamfarquhar** [comment]
I like putting it into the Parser. Some might argue for subclassing the Parser for those that need/want a classmap. I think that having a classmap is pretty important for making sense of the data, however, and not just because of the differences in using strings/numbers. It also documents what background is.

**Comment by lgvaz** [comment]
So, I've been thinking of ways to integrate class_map as an attribute of the parser, let me share some of the issues I'm facing

On inference, we need to instantiate the class_map but we don't need to instantiate the Parser, this shows that the class_map should be somehow *injected* into the parser, maybe as an argument to the constructor.

So for example, the Parser returned by `parsers.coco` would already have the class_map injected.

There are two main issues with this approach:
1. The methodology of getting a class_map for training and inference would differ, we save some lines on training at the expense of making the user learn another approach for inference.
2. A more technical problem, the current Parser implementation does not have a custom `__init__` for some reasons: when implementing a custom parser (subclassing from Parser) you normally need to implement a custom `__init__`, this injection would need the user to add the additional line of `super().__init__(class_map=class_map)` or something like that, this would be a breaking change. Actually any change to the base `__init__` signature would be a breaking change, I think we should avoid that.

Maybe there is some other way of achieving this that I'm missing, but my current reasoning is that the only way of making class_map an attribute of the Parser is via injection, but doing so has significant drawbacks.

**Comment by FraPochetti** [comment]
Not relevant anymore
