### ISSUE TITLE
Update CONTRIBUTING Guide

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#417]
## 📓 Documentation Update
Add info about how to resolve conflicts in the CONTRIBUTING Guide

**Comment by lee00286** [comment]
Can I work on this issue?

**Comment by ai-fast-track** [comment]
Hi @lee00286, 

We are very happy you are interested in our project. You can work on this issue. I would like to mention that we need these changes done in the next couple of days due to the fact we intend to officially release  IceVision early next week. I you have time to do it, we will be happy to assist you in that process.

If, for any reason, you don't have the time to do it, don't worry there will be a plenty of opportunities to contribute to our projects (IceVision and [IceData](https://github.com/airctic/icedata) as we are very actively working on them. 

If you are interested, you can [join our Devs Forum](https://discord.gg/QxHctJF): There is no obligation to join in order to contribute to the project!
