### ISSUE TITLE
Remove conda section from installation instructions

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#422]
Since we moved to Poetry, should we remove the conda section from the installation instructions?

Poetry will already create a virtual env for the project if no virtual env is already activated, and if you are already using conda, it'll work transparently.

It will be required to also update the contributing guide, as it's referencing to the "conda install" option.

**Comment by lgvaz** [comment]
It might also be a good idea to remove the "installing from git" option.

I don't see a real use case for it unless you're using colab and want to install from master, but in that case there is the additional step `pip install jsonschema --upgrade` to get it working.

So maybe, we can have a section that is: "Bleeding edge install on Colab" or something like that

**Comment by potipot** [comment]
Conda file has been updated and will be kept for now as it is the easiest way to install icevision now. In the future might consider releasing icevision to conda repository to be able to do `conda install icevision`
