### ISSUE TITLE
Importing from the old library

### ISSUE THREAD

**Issue by muellerzr** [airctic/icevision#434]
## 🐛 Bug
**Describe the bug**
Currently imports.py calls `import fastai2.vision.all`. `fastai2` is no longer the home, it's `fastai`. As a result the API is a bit behind, leading to a few other bugs further down the pipeline (because it's searching fastai2, not fastai)

**To Reproduce**
1. `pip install fastai --upgrade`
2. `from icevision.all import *`

**Expected behavior**
No errors being run

**Desktop (please complete the following information):**
 - Google Colab

**Comment by lgvaz** [comment]
This is also a good first issue for starting contributing to the library, I'll tag it so anyone interested can pick it up =)

**Comment by FraPochetti** [comment]
Let me take a stab to this one.
I should have some time today.

**Comment by lgvaz** [comment]
It will be necessary to update both fastai and fastcore at the same time (because they co-depend), the first error you encounter will probably be related to the `Tuple` to `fasttuple` renaming.

Anyways, if you have any problems feel free to share it here, glhf!

**Comment by muellerzr** [comment]
Another good way to see what all the changes were is to take a look at this thread, there's also tips for automating the changes: https://forums.fast.ai/t/major-new-changes-and-features/40742

**Comment by bguan** [comment]
Hi, playing w IceVision and ran into this issue #434.  Anyone working on this?  I can take it on if nobody is working on it.

**Comment by FraPochetti** [comment]
Hi @bguan I was supposed to look into it yesterday but I am having unexpected personal commitments which will keep me busy for the next couple or days. Please feel free to go ahead and grab it. Just let me know if you do so, to avoid stepping onto each other's toes.

**Comment by bguan** [comment]
@FraPochetti I am happy to take a stab, i think its mostly done, just tracking down 2 test failures from FastAI's learner.

**Comment by bguan** [comment]
I submitted a PR for this issue, please review at your earliest convenience. https://github.com/airctic/icevision/pull/454

**Comment by lgvaz** [comment]
closed with #454
