### ISSUE TITLE
[Discussion] Tutorials and Examples

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#440]
Each tutorial is mirroed with an example, the main idea is that examples are easy copied to the clipboard (single click copy all).

However, I see two immediate issues with this approach:
* It's hard to maintain both, whenever we want to modify something we have to modify in two places
* It confuses people, it's not immediatily clear why we have tutorials and examples

At the end of the day, I don't think it's worth having both just so it's easier to copy code.

@adamfarquhar , @ai-fast-track can I get your thoughts on this?

**Comment by ai-fast-track** [comment]
We can automate how to generate the examples using the notebooks. We can use a technique similar to the one used by fastai (# export) to only extract the relevant code (used for copy&paste operation) for the examples.

**Comment by FraPochetti** [comment]
Not relevant anymore.
We are trying to unify the notebooks and tutorials
