### ISSUE TITLE
Deployment section on docs

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#445]
## 📓 Documentation Update
Currently the deployment docs are manually added, somehow we need to get the notebook that is on the gradio notebook to display on icevision documentation.

## Option 1
Clone the repo on `autogen.py` and read the notebooks this way.

## Option 2
Download the notebook directly from the URL.

## Potential issue
If testing the documentation locally, this would mean that everytime you run `autogen.py` the notebooks are going to be downloaded.

We can restructure `autogen.py` to receive arguments in such a way that by default notebooks are not re-downloaded if already present.

**Comment by lgvaz** [comment]
The quick fix solution taken was to just to manually copy the files

**Comment by FraPochetti** [comment]
@ai-fast-track I don't think we need a specific deployment section.
We'll have the new Resources section with links to blog posts.
Wdyt?

**Comment by FraPochetti** [comment]
Closing.
