### ISSUE TITLE
Which parser should be used for the EfficentDet?

### ISSUE THREAD

**Issue by tugot17** [airctic/icevision#464]
## 📓 Documentation Update
**What part of documentation was unclear or wrong?**
It is not clear for me which parser should I extend if I want to use `Efficendet` module

**Describe the solution you'd like**
Example similar to the Custom dataset from the docs, but with Efficentdet

**Additional context**
I tried just using the FasterRCNN parser with Efficentdet but I get error:

```python
TypeError: forward() missing 1 required positional argument: 'target'
```

**Comment by lgvaz** [comment]
Hm... The parsers used for faster_rcnn and efficientdet should be exactly the same, this problem is originating from somewhere else

Can you provide the full stack trace? What engine are you using to train? What version of icevision are you using? (check with `icevision.__version__`)

**Comment by tugot17** [comment]
I use Pytorch Lightning on google colab, installed with icevision[all]

```python
TypeError                                 Traceback (most recent call last)

<ipython-input-48-860a67f9c1e3> in <module>()
      1 trainer = pl.Trainer(max_epochs=30, gpus=1, logger=tb_logger, early_stop_callback=True)
----> 2 trainer.fit(light_model, train_dl, valid_dl)

10 frames

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

TypeError: forward() missing 1 required positional argument: 'target'
```

`Iceviso version: 0.1.5`

**Comment by lgvaz** [comment]
Can you share how you are creating your dataloaders?

This *might* happen if you are using `efficientdet.valid_dl` to create the train dataloader (my first guess, because I don't think this is parser/dataset related)

**Comment by tugot17** [comment]
I think I have found the issue, it wasn't the parser, it was the `LightModel`. Apparently it is important which `ModelAdapter` is used, sorry for the trouble 

```
class LightModel(efficientdet.lightning.ModelAdapter):
    def configure_optimizers(self):
        return Adam(self.parameters(), lr=1e-3)
```
