### ISSUE TITLE
Tutorial rename `width,height` to `image_width,image_height`

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#469]
## 📓 Documentation Update
With #462 the parser methods `width` and `height` got renamed to `image_width` and `image_height`, the tutorials have to be updated to reflect this renaming.

**Comment by FaMoSi** [comment]
Can I work on this?

**Comment by lgvaz** [comment]
Yes, thanks!! I'll assign you to the issue

**Comment by FaMoSi** [comment]
Hi @lgvaz, in the issue description you talk about "tutorials". What do you mean with the word "tutorials"? Can you specify which files have to be updated? :)

**Comment by lgvaz** [comment]
Yeah, so we need to update the files under `notebooks` and `examples`

**Comment by FaMoSi** [comment]
I updated the files to reflect #462. The pull request is #473. 

Let me know if everything is ok ✅

I'm participating to `hacktoberfest2020`. Can you please add the `hacktoberfest-accepted` label to the PR? Thanks 😊

**Comment by lgvaz** [comment]
Thanks @FaMoSi !! I'll check out the PR later today

>  Can you please add the hacktoberfest-accepted label to the PR?

For sure! Just did that =)
