### ISSUE TITLE
Rotated Bounding boxes.

### ISSUE THREAD

**Issue by oke-aditya** [airctic/icevision#471]
## 🚀 Feature
A bit unsure about this feature.

Support Rotated Bounding Boxes in Torchvision.

## Motivation

There is recent research on Rotated Bounding boxes which provides better detection results. I am not able to find highly cited results but a few of them are
1. [Rotation Invariant Detector](https://arxiv.org/pdf/1711.09405v1.pdf)
2. [SCRDET](https://openaccess.thecvf.com/content_ICCV_2019/papers/Yang_SCRDet_Towards_More_Robust_Detection_for_Small_Cluttered_and_Rotated_ICCV_2019_paper.pdf) ICCV 2019.

I'm not sure for more papers. I think this is slightly new topic, and needs a bit more research.

## Pitch

1. Support operations for Rotated Bounding boxes, NMS, ROI Align. IoU.
2. Support Augmentation (if needed) for Rotated Bounding boxes.
3. Support such Datasets (if any) that use Rotated Boxes. 

If possible we can also support Rotated models. In my opinion it might not be very feasible. 
Since it will take a lot of time and maintenance for these models.

## Alternatives

Currently, Detectron2 has great support for all the above. These operations are implemented in C++.

## Additional context

Looks tricky and challenging. I guess it might also be too early to think about this. I think it needs a bit more research and some baseline.

**Comment by oke-aditya** [comment]
Thoughts @lgvaz. Native support might come with torchvision. But we have abstracted out `Bbboxes` here.
There are lot of operations that need CUDA support for these and need to be done in C++ only. I'm not sure how these can be handled, here.

**Comment by lgvaz** [comment]
> Looks tricky and challenging. I guess it might also be too early to think about this. I think it needs a bit more research and some baseline.

Yeah, currently I don't have much time to looks into this, but it's definitly something to keep under our radar.

**Comment by FraPochetti** [comment]
Unfortunately not. This is not a priority for us, given the very limited bandwidth we have.
