### ISSUE TITLE
Fastcore 1.1 breaking changes

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#475]
## 🐛 Bug
**Describe the bug**
Fastcore 1.1 contains a breaking change described [here](https://github.com/fastai/fastcore/blob/master/CHANGELOG.md):
- Remove Path.{read,write} (use Path.{read_text,write_text} instead) and change Path.{load,save} to functions load_pickle and save_pickle (#121)

We need to update our calls to `Path.read` to fix this issue.

**Comment by FraPochetti** [comment]
As far as I can tell we have only 2 occurrences of `pathlib.Path.read()` in the codebase: [here](https://github.com/airctic/icevision/blob/0b174a738366417d0b74c23d1d4866a93723d4d6/icevision/test_utils/samples.py#L16) and [here](https://github.com/airctic/icevision/blob/0b174a738366417d0b74c23d1d4866a93723d4d6/icevision/parsers/coco_parser.py#L13).
Is this correct?

**Comment by FraPochetti** [comment]
If this is the case I can quickly patch it. It should be a matter of replacing `.read()` with either `.read_text()` or `.read_bytes()`. They both work with `json.loads(...)`

**Comment by lgvaz** [comment]
> Is this correct?

I believe you're correct, I did a global search and the other `read`s that I found seem not to be related with `Path`

> If this is the case I can quickly patch it.

That would be very much appreciated ❤️, I'm guessing that `read_text` returns a string just like `read` does right?

**Comment by lgvaz** [comment]
I also opened the reflecting issue on [icedata](https://github.com/airctic/icedata/issues/63).

It's not necessary to fix the issue there to fix it here, but I just wanted to let you know in case you're interested.

**Comment by FraPochetti** [comment]
Sure man! Will do that tomorrow ;). I will also check `icedata`.

> I'm guessing that read_text returns a string just like read does right?

Yes.

**Comment by lgvaz** [comment]
Thanks!!

**Comment by lgvaz** [comment]
Should I assign the issue to you? So other people know it's already taken

**Comment by FraPochetti** [comment]
Yes please
