### ISSUE TITLE
[Update] Albumentations 0.5.0

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#501]
## 🐛 Bug
The new release of albumentations 0.5.0 introduced breaking changes, the error is currently being avoided by specifying a version lower than 0.5.0 in `setup.cfg`

**How to reproduce**
Update albumentations and run: `pytest tests/transforms/test_albu_transform.py `

**Stracktrace**
```python
 internal_data_name = 'masks'

    def _check_args(self, **kwargs):
        checked_single = ["image", "mask"]
        checked_multi = ["masks"]
        # ["bboxes", "keypoints"] could be almost any type, no need to check them
        for data_name, data in kwargs.items():
            internal_data_name = self.additional_targets.get(data_name, data_name)
            if internal_data_name in checked_single:
                if not isinstance(data, np.ndarray):
                    raise TypeError("{} must be numpy array type".format(data_name))
            if internal_data_name in checked_multi:
>               if data:
E               ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/albumentations/core/composition.py:223: ValueError
```

**Comment by FraPochetti** [comment]
I think I might benefit from learning how to effectively debug, so I can take this one if you accept.

**Comment by lgvaz** [comment]
Thanks Francesco!!! You're on fire 🔥

**Comment by FraPochetti** [comment]
I think I found the culprit.
The problem is in the `tfms` applied to `masks`.
[This](https://github.com/airctic/icevision/blob/7314dd0ba60d89cf96305e51262466ed13549b77/icevision/tfms/albumentations/tfms.py#L108) line should look like `params["masks"] = list(masks.data)`.
In the `albumentations` docs they specify that `masks` needs to be a `list` ([here](https://albumentations.ai/docs/getting_started/mask_augmentation/#step-4-pass-image-and-masks-to-the-augmentation-pipeline-and-receive-augmented-images-and-masks)).
I made the edit and now tests are passing.
Before I create a PR, does this make sense to you?

**Comment by FraPochetti** [comment]
Also, not sure how to handle the dependency.
Assuming the fix works, shall we also edit [this](https://github.com/airctic/icevision/blob/7314dd0ba60d89cf96305e51262466ed13549b77/setup.cfg#L29) line removing the `<0.5` constraint?
I mean, in the same PR.

**Comment by FraPochetti** [comment]
I also tested the change (e.g. `params["masks"] = list(masks.data)`) with `albumentations` version `0.4.6` and it still works, so it looks backwards compatible.

**Comment by lgvaz** [comment]
> This line should look like params["masks"] = list(masks.data)

Interesting, for some reason they decided not to accept a numpy array anymore?

> Before I create a PR, does this make sense to you?

Yeah yeah! To get the tests passing were the only thing required on this one

> I mean, in the same PR.

Yes, both changes in the same PR, but instead of removing the condition put it `<0.6`, so it doesn't break unexpectedly in the future

**Comment by FraPochetti** [comment]
[PR](https://github.com/airctic/icevision/pull/509) created!
