### ISSUE TITLE
Keypoint detection

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#502]
## 🚀 Feature
Torchvision includes the [keypoint rcnn](https://pytorch.org/docs/stable/torchvision/models.html#keypoint-r-cnn) that should work very similarly to the other rcnn models. It should be straight forward to add support for this task.

**TODO list**
- [ ] Datastructure: `Keypoints`
- [ ] Record mixin
- [ ] Parser mixin
- [ ] Dataloders 
- [ ] Model
- [ ] predict, predict_dl
- [ ] Visualization

**Comment by FraPochetti** [comment]
I can help with this one if you guys are up to the challenge of providing guidance to a newbie with the library! :)

**Comment by lgvaz** [comment]
Francesco, I'm so happy you commented on this one! We're going to have such a good time implementing this!

Let's start discussing this more over the next weekend, we can have some meetings on discord where we can discuss strategies on how to implement this, it will be a collective effort, what do you think?

**Comment by FraPochetti** [comment]
Totally agree!

**Comment by lgvaz** [comment]
uhuu @FraPochetti, we forgot to close this very important one hahahah

**Comment by FraPochetti** [comment]
Indeed!
