### ISSUE TITLE
Can't pickle local object FastaiDataLoaderWithCollate

### ISSUE THREAD

**Issue by dodoslav** [airctic/icevision#511]
## 🐛 Bug
**Describe the bug**
Cannot train in `mask_rcnn_pennfudan.ipynb` with defaults params.

**To Reproduce**
1. `git clone https://github.com/airctic/icevision.git`
2. open `mask_rcnn_pennfudan.ipynb` notebook
3. run all code in the notebook
4. when running `learn.fine_tune(10, 5e-4, freeze_epochs=2)` cell getting this error: `Can't pickle local object 'convert_dataloader_to_fastai.<locals>.FastaiDataLoaderWithCollate'`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
- conda 4.9.0
- icedata 0.1.0    
- icevision 0.2.1.post1   
- python 3.6.12
- fastai 2.0.16
- pytorch 1.6.0 

**Additional context**

**Comment by lgvaz** [comment]
I cannot reproduce the issue when running the notebook on [colab](https://colab.research.google.com/github/airctic/icevision/blob/master/notebooks/mask_rcnn_pennfudan.ipynb)

Is there anything you modified on the notebook? Also, can you post the full stack trace here?

**Comment by dodoslav** [comment]
Hi, it is working in colab, my windows is complaining. 
It did not modify the notebook.
here is stacktrace:
`
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-e7575ffee816> in <module>
----> 1 learn.fine_tune(10, 5e-4, freeze_epochs=2)

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastcore\logargs.py in _f(*args, **kwargs)
     54         init_args.update(log)
     55         setattr(inst, 'init_args', init_args)
---> 56         return inst if to_return else f(*args, **kwargs)
     57     return _f

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\callback\schedule.py in fine_tune(self, epochs, base_lr, freeze_epochs, lr_mult, pct_start, div, **kwargs)
    159     "Fine tune with `freeze` for `freeze_epochs` then with `unfreeze` from `epochs` using discriminative LR"
    160     self.freeze()
--> 161     self.fit_one_cycle(freeze_epochs, slice(base_lr), pct_start=0.99, **kwargs)
    162     base_lr /= 2
    163     self.unfreeze()

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastcore\logargs.py in _f(*args, **kwargs)
     54         init_args.update(log)
     55         setattr(inst, 'init_args', init_args)
---> 56         return inst if to_return else f(*args, **kwargs)
     57     return _f

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\callback\schedule.py in fit_one_cycle(self, n_epoch, lr_max, div, div_final, pct_start, wd, moms, cbs, reset_opt)
    111     scheds = {'lr': combined_cos(pct_start, lr_max/div, lr_max, lr_max/div_final),
    112               'mom': combined_cos(pct_start, *(self.moms if moms is None else moms))}
--> 113     self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd)
    114 
    115 # Cell

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastcore\logargs.py in _f(*args, **kwargs)
     54         init_args.update(log)
     55         setattr(inst, 'init_args', init_args)
---> 56         return inst if to_return else f(*args, **kwargs)
     57     return _f

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
    205             self.opt.set_hypers(lr=self.lr if lr is None else lr)
    206             self.n_epoch = n_epoch
--> 207             self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
    208 
    209     def _end_cleanup(self): self.dl,self.xb,self.yb,self.pred,self.loss = None,(None,),(None,),None,None

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in _with_events(self, f, event_type, ex, final)
    153 
    154     def _with_events(self, f, event_type, ex, final=noop):
--> 155         try:       self(f'before_{event_type}')       ;f()
    156         except ex: self(f'after_cancel_{event_type}')
    157         finally:   self(f'after_{event_type}')        ;final()

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in _do_fit(self)
    195         for epoch in range(self.n_epoch):
    196             self.epoch=epoch
--> 197             self._with_events(self._do_epoch, 'epoch', CancelEpochException)
    198 
    199     @log_args(but='cbs')

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in _with_events(self, f, event_type, ex, final)
    153 
    154     def _with_events(self, f, event_type, ex, final=noop):
--> 155         try:       self(f'before_{event_type}')       ;f()
    156         except ex: self(f'after_cancel_{event_type}')
    157         finally:   self(f'after_{event_type}')        ;final()

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in _do_epoch(self)
    189 
    190     def _do_epoch(self):
--> 191         self._do_epoch_train()
    192         self._do_epoch_validate()
    193 

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in _do_epoch_train(self)
    181     def _do_epoch_train(self):
    182         self.dl = self.dls.train
--> 183         self._with_events(self.all_batches, 'train', CancelTrainException)
    184 
    185     def _do_epoch_validate(self, ds_idx=1, dl=None):

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in _with_events(self, f, event_type, ex, final)
    153 
    154     def _with_events(self, f, event_type, ex, final=noop):
--> 155         try:       self(f'before_{event_type}')       ;f()
    156         except ex: self(f'after_cancel_{event_type}')
    157         finally:   self(f'after_{event_type}')        ;final()

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\learner.py in all_batches(self)
    159     def all_batches(self):
    160         self.n_iter = len(self.dl)
--> 161         for o in enumerate(self.dl): self.one_batch(*o)
    162 
    163     def _do_one_batch(self):

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\fastai\data\load.py in __iter__(self)
    100         self.before_iter()
    101         self.__idxs=self.get_idxs() # called in context of main process (not workers/subprocesses)
--> 102         for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
    103             if self.device is not None: b = to_device(b, self.device)
    104             yield self.after_batch(b)

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\site-packages\torch\utils\data\dataloader.py in __init__(self, loader)
    735             #     before it starts, and __del__ tries to join but will get:
    736             #     AssertionError: can only join a started process.
--> 737             w.start()
    738             self._index_queues.append(index_queue)
    739             self._workers.append(w)

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\multiprocessing\process.py in start(self)
    103                'daemonic processes are not allowed to have children'
    104         _cleanup()
--> 105         self._popen = self._Popen(self)
    106         self._sentinel = self._popen.sentinel
    107         # Avoid a refcycle if the target function holds an indirect

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\multiprocessing\context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224 
    225 class DefaultContext(BaseContext):

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\multiprocessing\context.py in _Popen(process_obj)
    320         def _Popen(process_obj):
    321             from .popen_spawn_win32 import Popen
--> 322             return Popen(process_obj)
    323 
    324     class SpawnContext(BaseContext):

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\multiprocessing\popen_spawn_win32.py in __init__(self, process_obj)
     63             try:
     64                 reduction.dump(prep_data, to_child)
---> 65                 reduction.dump(process_obj, to_child)
     66             finally:
     67                 set_spawning_popen(None)

~\AppData\Local\Continuum\miniconda3\envs\my_env\lib\multiprocessing\reduction.py in dump(obj, file, protocol)
     58 def dump(obj, file, protocol=None):
     59     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 60     ForkingPickler(file, protocol).dump(obj)
     61 
     62 #

AttributeError: Can't pickle local object 'convert_dataloader_to_fastai.<locals>.FastaiDataLoaderWithCollate'
`

**Comment by lgvaz** [comment]
Hmm, so the problem is specific to Windows, @ai-fast-track can you reproduce the issue?

**Comment by dodoslav** [comment]
No, i'm not using WSL. just pure windows. Do you recommend to use at least WSL ?

**Comment by lgvaz** [comment]
Yes, actually we officially only support Linux, but other users are using WSL without problems, @ai-fast-track included

**Comment by FraPochetti** [comment]
@dodoslav I confirm I am using WSL2 too, without issues so far.

**Comment by dodoslav** [comment]
Ok thank you guys !
