### ISSUE TITLE
Convert records to coco possible bug with masks

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#514]
With #510 all masks are being encoded to compressed RLE format

This affects the `convert_record_to_coco_annotations` function and the following hack was added:
```python
        if isinstance(masks, EncodedRLEs):
            annotations_dict["segmentation"] = masks.erles
```

We're simply setting `segmentation` to the encoded RLEs, but **I don't know** if the pycocotools COCO metric calculation works correctly with encoded RLEs.

The following hack also had to be added to `test_convert_records_to_coco_style_annotations`, because there was no easy way of comparing the converted segmentations (encoded RLEs) with the original segmentations (Polygons and RLEs).
```python
            if k1 == "segmentation":
                # TODO: Skipping segmentation check
                pass
```

**Comment by FraPochetti** [comment]
Not relevant anymore. The API got completely refactored.
