### ISSUE TITLE
Add more info in record auto-fixing

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#525]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**

1- parser.parser() emits messages about records auto-fixing that are no clear enough:

example: 
```bash
INFO     - Autofixing records | icevision.parsers.parser:parse:124
AUTOFIX  - ️🔨  Autofixing record with imageid: 2163  ️🔨 | icevision.core.record:_pre_replay:81
AUTOFIX  - Clipping bbox ymax from 1479 to image height 1152 | icevision.core.bbox:autofix:77
AUTOFIX  - Failed to fix: <BBox (xmin:103, ymin:1222, xmax:653, ymax:1152)> | icevision.core.record_mixins:_autofix:153
AUTOFIX  - Clipping bbox ymax from 1284 to image height 1152 | icevision.core.bbox:autofix:77
AUTOFIX  - Removed annotation with index: 0 | icevision.core.record:autofix:34
```

We should add the reason why the annotation was removed. In this case the reason is that ` ymin:1222` > `ymax:1152`. We should relay the related info to the final message: `AUTOFIX  - Removed annotation with index: 0 | icevision.core.record:autofix:34`

2- For better readibilty, use colors with better contrast:
![image](https://user-images.githubusercontent.com/59614262/98007415-5eb8e000-1dc1-11eb-96c5-29271c22660b.png)

**Comment by lgvaz** [comment]
I changed the normal "AUTOFIX" colors to be more friendly with light backgrounds

For 1., it's difficult to relay the message at the end, but I added a new tag `AUTOFIX-FAIL` that should help visualization:

![image](https://user-images.githubusercontent.com/16520544/98130813-6b106c00-1e99-11eb-9e08-ba874953d126.png)

![image](https://user-images.githubusercontent.com/16520544/98130845-75326a80-1e99-11eb-80f9-44f3b231e80f.png)

**Comment by lgvaz** [comment]
New colors:

![image](https://user-images.githubusercontent.com/16520544/98177600-c3675e00-1ed9-11eb-91ad-dc63ce164343.png)

![image](https://user-images.githubusercontent.com/16520544/98177613-cc582f80-1ed9-11eb-9821-13f1953cedee.png)

**Comment by lgvaz** [comment]
In colab:

![image](https://user-images.githubusercontent.com/16520544/98178940-6e791700-1edc-11eb-99da-770ad23ca356.png)

![image](https://user-images.githubusercontent.com/16520544/98178955-7afd6f80-1edc-11eb-96d1-fa7188607e9e.png)

**Comment by lgvaz** [comment]
I just changed to brown to a slight lighter one:

![image](https://user-images.githubusercontent.com/16520544/98179143-e6dfd800-1edc-11eb-9e58-f110ed3bd0b6.png)
