### ISSUE TITLE
Visualizing small bboxes

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#545]
## 🐛 Bug
As shown in the image below the visualization of small instances don't look good, this happens because the corners of the bboxes have a fixed size and are independent of the size of the object (so small objects are dominated by the corners)

The function to be modified is: `visualize/draw_data.py::draw_bbox`

![image](https://user-images.githubusercontent.com/16520544/99150444-63a84a00-2673-11eb-84d7-19e29bc2f44b.png)

**Comment by RibenaMapleSyrup** [comment]
Currently looking at this.

**Comment by lgvaz** [comment]
closed with #575 , thanks @RibenaMapleSyrup !!!!
