### ISSUE TITLE
Tutorial on writing a custom RecordMixin, to show how to read in special file formats like 16 bit gray scale or Dicom

### ISSUE THREAD

**Issue by fstroth** [airctic/icevision#560]
Is there a dataset in icedata that can be used for this example, or do we need to get data from somewhere?
I don't intend to include any example of training a NN in the tutorial, only data reading and augmentation.

---
**Don't remove**
Main issue for examples: #39

**Comment by lgvaz** [comment]
Currently we don't have any datasets using dicom or 16bit gray, would you like to create a tutorial on that?

After the tutorial is complete it would be super awesome to also add the dataset to icedata
