### ISSUE TITLE
Parser Type Error() on using example code at https://airctic.com/examples/getting_started_exp/

### ISSUE THREAD

**Issue by Theivaprakasham** [airctic/icevision#562]
## 🐛 Bug
**Describe the bug**
I am receiving Parser Type Error() on using example code at https://airctic.com/examples/getting_started_exp/.

TypeError                                 Traceback (most recent call last)

<ipython-input-5-b8282c4e87f3> in <module>()
     12 # PETS parser: provided out-of-the-box
     13 parser = icedata.pets.parser(data_dir=path, class_map=class_map)
---> 14 train_records, valid_records = parser.parse(data_splitter)
     15 
     16 # shows images with corresponding labels and boxes

/usr/local/lib/python3.6/dist-packages/icevision/parsers/parser.py in parse(self, data_splitter, idmap, autofix, show_pbar, cache_filepath)
    119             records = self.parse_dicted(show_pbar=show_pbar, idmap=idmap)
    120 
--> 121             splits = data_splitter(idmap=idmap)
    122             all_splits_records = []
    123             if autofix:

TypeError: 'module' object is not callable

**To Reproduce**
1. Go to 'https://airctic.com/examples/getting_started_exp/'
2. Click on 'Fastai/Pytorch Lightning implementation code at Training and End-to-End dataset (PETS)'
3. Install the dependency using **!pip install icevision[all] icedata**
4. Run the following code.

```
# Imports
from icevision.all import *
import icedata

# Load the PETS dataset
path = icedata.pets.load_data()

# Get the class_map, a utility that maps from number IDs to classs names
class_map = icedata.pets.class_map()



# PETS parser: provided out-of-the-box
parser = icedata.pets.parser(data_dir=path, class_map=class_map)
train_records, valid_records = parser.parse(data_splitter)

# shows images with corresponding labels and boxes
show_records(train_records[:6], ncols=3, class_map=class_map, show=True)

# Define transforms - using Albumentations transforms out of the box
train_tfms = tfms.A.Adapter(
    [*tfms.A.aug_tfms(size=384, presize=512), tfms.A.Normalize()]
)
valid_tfms = tfms.A.Adapter([*tfms.A.resize_and_pad(size), tfms.A.Normalize()])
# Create both training and validation datasets
train_ds = Dataset(train_records, train_tfms)
valid_ds = Dataset(valid_records, valid_tfms)

# Create both training and validation dataloaders
train_dl = faster_rcnn.train_dl(train_ds, batch_size=16, num_workers=4, shuffle=True)
valid_dl = faster_rcnn.valid_dl(valid_ds, batch_size=16, num_workers=4, shuffle=False)

# Create model
model = faster_rcnn.model(num_classes=len(class_map))

# Define metrics
metrics = [COCOMetric(metric_type=COCOMetricType.bbox)]

# Train using fastai2
learn = faster_rcnn.fastai.learner(
    dls=[train_dl, valid_dl], model=model, metrics=metrics
)
learn.fine_tune(10, lr=1e-4)
```
https://guides.github.com/features/mastering-markdown/
5. See an Type error in Parse:

```
**100%
791918971/791918971 [01:09<00:00, 11384298.60B/s]


100%
19173078/19173078 [00:03<00:00, 4870576.75B/s]


100%
3686/3686 [00:00<00:00, 5723.73it/s]


---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-5-b8282c4e87f3> in <module>()
     12 # PETS parser: provided out-of-the-box
     13 parser = icedata.pets.parser(data_dir=path, class_map=class_map)
---> 14 train_records, valid_records = parser.parse(data_splitter)
     15 
     16 # shows images with corresponding labels and boxes

/usr/local/lib/python3.6/dist-packages/icevision/parsers/parser.py in parse(self, data_splitter, idmap, autofix, show_pbar, cache_filepath)
    119             records = self.parse_dicted(show_pbar=show_pbar, idmap=idmap)
    120 
--> 121             splits = data_splitter(idmap=idmap)
    122             all_splits_records = []
    123             if autofix:

TypeError: 'module' object is not callable**
```

**Desktop (please complete the following information):**
 - OS: Linux (Google Colab with GPU)

**Comment by lgvaz** [comment]
The solution is to remove `data_splitter` from the function call, we're now using the default option for that argument.

Would you like to open a PR fixing the issue?

**Comment by FraPochetti** [comment]
Not relevant anymore
