### ISSUE TITLE
Plot Top Losses

### ISSUE THREAD

**Issue by RibenaMapleSyrup** [airctic/icevision#563]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**
I would like to plot top losses for predictions made by a trained model. This would be really useful to help me figure out where my trained model is making mistakes. With show_results I can view a model's predictions however loss would also be useful as loss encompasses how confident the model is. With this additional information I could better clean my dataset and work towards improving accuracy. 

**Describe the solution you'd like**
I would like to write a function that accepts samples and predictions as input parameters and outputs an ordered dictionary pairing samples with loss values. 

**Describe alternatives you've considered**

**Additional context**
It doesn't seem possible to calculate loss when model is in evaluation mode.

**Comment by FraPochetti** [comment]
Hey @lgvaz, can you please assign me to this one?

**Comment by FraPochetti** [comment]
Feature implemented [here](https://github.com/airctic/icevision/pull/589).
Closing.

**Comment by RibenaMapleSyrup** [comment]
Awesome work!! Look forward to working with this feature. Thanks so much :D
