### ISSUE TITLE
Keypoint tests uses OCHuman dataset

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#571]
Some of the keypoints tests are done using the OCHuman dataset, but the parser for this dataset is not implemented in `icevision` (currently it's being defined inside `conftest.py`).

Instead we should do all tests using COCO keypoints, OCHuman should be moved to `icedata`.

**Comment by FraPochetti** [comment]
We need to create a keypoints-COCO-sample for that to happen, no?

**Comment by lgvaz** [comment]
Correcto!

**Comment by FraPochetti** [comment]
Not relevant anymore.
