### ISSUE TITLE
Tutorial for how to use FixedSplitter 

### ISSUE THREAD

**Issue by RibenaMapleSyrup** [airctic/icevision#585]
## 📓 New <Tutorial/Example>
It would be useful to have a tutorial on how to use FixedSplitter when parsing dataset with predefined splits for train, test and validation. 

This tutorial would be relevant to any icevision task as it focusses on preparing our dataset. 

I'm not sure which dataset would be most appropriate for this tutorial but I would like to see FixedSplitter applied to a Pascal VOC formatted dataset where splits are derived from those specified by defined ImageSets.

---
**Don't remove**
Main issue for examples: #39

**Comment by RibenaMapleSyrup** [comment]
Happy to look at this!

**Comment by lgvaz** [comment]
Thanks a lot @RibenaMapleSyrup! I just assigned the issue to you
