### ISSUE TITLE
resnest module not found preventing imports

### ISSUE THREAD

**Issue by RibenaMapleSyrup** [airctic/icevision#591]
## 🐛 Bug
'resnest' module cannot be found when we attempt to import it within icevision/backbones/resnest_fpn.py. I noticed this bug when trying to import all packages from icevision within a Jupyter Notebook and the process failed.

1. Make sure you are using the latest version of the library
2. Run "from icevision.all import *" within your notebook or python file
3. The process should fail with: "ModuleNotFoundError: No module named 'resnest'"

When I comment out "import resnest.torch" within icevision/backbones/resnest_fpn.py , my imports complete with no error, so I believe this is the only import causing issues.

I am running icevision via Jupyter Notebooks within a Ubuntu environment

**Comment by lgvaz** [comment]
Hi! Thanks for opening the issue, PR #592 should fix this. Can you check once that's is merged and close this if it's solved?

**Comment by RibenaMapleSyrup** [comment]
Awesome thank you, will do!

**Comment by lgvaz** [comment]
just merged =)

**Comment by RibenaMapleSyrup** [comment]
Fantastic, just ran- no errors :D
