### ISSUE TITLE
"wandb_img_preds" method gives error when "add_ground_truth=True"

### ISSUE THREAD

**Issue by bnapora** [airctic/icevision#598]
## 🐛 Bug
**Describe the bug**
wandb_img_preds(samples, preds, class_map, add_ground_truth=True) function gives an error when add_ground_truth=True.  When add_ground_truth=False, then images are returned.  

It looks like there maybe a formatting issue when the "ground_truth" data is appended to "predictions" data in the wandb_image() function. 

I'm curious to see if anyone else is having this issue.

**To Reproduce**
I'm using a Custom Dataparser, but don't believe the issue is related to that, since method works when ground_truth is set to False.
1. Running latest code from master branch installed via pip into dedicated env
2. Call wandb_img_preds and set "add_ground_truth=True"

I can provide a notebook to illustrate issue if no one can duplicate.

**Expected behavior**
Method should return Ground Truth & Prediction images 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Comment by lgvaz** [comment]
@ai-fast-track I'm tagging you since you implemented this functionality, did you also faced this error before?

**Comment by FraPochetti** [comment]
Closing.
