### ISSUE TITLE
Video Object Segmentation Support

### ISSUE THREAD

**Issue by rsomani95** [airctic/icevision#605]
Stemming from [this discussion](https://discord.com/channels/735877944085446747/750082588068151457/798169003117772810) on the Discord chat, we should eventually support video data loading and models in icevision. 

### Models
Here are two state of the art papers in the space:
1. CFBI [[GitHub]](https://github.com/z-x-yang/CFBI) [[Paper]](https://arxiv.org/abs/2003.08333)
2. STM (Space-Time Memory) Network [[GitHub]](https://github.com/seoungwugoh/STM) [[Paper]](https://openaccess.thecvf.com/content_ICCV_2019/html/Oh_Video_Object_Segmentation_Using_Space-Time_Memory_Networks_ICCV_2019_paper.html)

[PapersWithCode](https://paperswithcode.com/task/semi-supervised-video-object-segmentation) for Video Object Segmentation (VOS)

For CFBI, the training code is not released, but the author mentions that we could email them asking for the same. The repo has a BSD license, so I presume they'd be open to integrating a training pipeline with icevision?

### Datasets
As for datasets, there's two popular datasets models are typically benchmarked against in this space:
1. [DAVIS](https://davischallenge.org/)
2. [YouTube-VOS](https://youtube-vos.org/)

I'm somewhat familiar with the data format for YouTube-VOS -- they provide every 5th frame of the video as a JPEG image, so there's no real video loading required there. However, we should eventually build an base API that can load frames from videos and adapters for different datasets?

---

VOS models typically take an input mask that they track for the duration of the video. Eventually, it would be awesome to pipe the outputs from a Mask-RCNN like model into a VOS model.

**Comment by rsomani95** [comment]
Relevant library: https://github.com/visionml/pytracking

**Comment by FraPochetti** [comment]
Not enough bandwidth to implement
