### ISSUE TITLE
Interpretation for mmdetection models

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#618]
## 🚀 Feature
Add interpretation (`plot_top_losses`) for mmdetection models

**Comment by lgvaz** [comment]
@FraPochetti interested in this one? =)

**Comment by FraPochetti** [comment]
Of course!

**Comment by FraPochetti** [comment]
From tomorrow I am gonna start working on this one ;)

**Comment by lgvaz** [comment]
> Maybe we should un-archive the #plot_top_loss channel so that I will post my thoughts there as we go?
Yeees! Will do!

**Comment by lgvaz** [comment]
@FraPochetti i believe this was done right? ahhahaha

**Comment by FraPochetti** [comment]
Yes!
