### ISSUE TITLE
Write tests for mmdet models

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#622]
## 🚀 Feature
Currently the newly added code is entirely untested

**Comment by FraPochetti** [comment]
I love this one #618 for obvious reasons :) but I'd rather start from here if I may.
Writing tests will help me dig into the library in more detail.
Can I get it?

**Comment by lgvaz** [comment]
> Can I get it?
Yes!! Thanks a looot!!

We can also chat in the forums to figure out what tests to implement =)

**Comment by FraPochetti** [comment]
I guess we can close this one :)

**Comment by FraPochetti** [comment]
@lgvaz :D

**Comment by lgvaz** [comment]
Ow, sry! Thanks for the reminder =)
