### ISSUE TITLE
Add support for YOLOv5

### ISSUE THREAD

**Issue by FraPochetti** [airctic/icevision#649]
## 🚀 Feature
We are currently working to add YOLOv3 from `mmdet`, but it would be nice to also have YOLOv5 from [Ultralytics](https://github.com/ultralytics/yolov5) as their implementation seems pretty stable.

**Comment by FraPochetti** [comment]
can you guys assign this to me, please?

**Comment by lgvaz** [comment]
done! thanks a lot!

**Comment by FraPochetti** [comment]
Done.
