### ISSUE TITLE
predict_dl returns empty array from Quickstart example

### ISSUE THREAD

**Issue by bhavints** [airctic/icevision#653]
## 🐛 Bug
**Describe the bug**
I am trying to run the [Quickstart ](https://airctic.com/examples/quickstart_exp/) example and keep running into an error. When I get to this line

`samples, preds = efficientdet.predict_dl(model, infer_dl)`

The preds are empty. I have verified that the model and infer_dl are not empty and seem to be valid. 

**To Reproduce**
Run the entire Quickstart and when you get to predictions, they will be empty after following all the steps.

**Screenshots**
![image](https://user-images.githubusercontent.com/31303862/108917528-bbe0d780-75e4-11eb-9fae-482e48586e95.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by FraPochetti** [comment]
We are going through all tutorial notebooks. This will be fixed.
