### ISSUE TITLE
mmdetection integration does not consistently handle background class (k versus 0 position)

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#661]
In MMDetection, the background class is k, not 0 (for k-1 classes).

Currently, show_results shows ground-truth with 0=background with predictions showing k=background and 0=first class.

![image](https://user-images.githubusercontent.com/454453/110256153-3cadb500-7f8f-11eb-9c8f-cab497d7d1f7.png)

The parser generates a class_map, but the dataloader needs to correct it (switching the background location) and doesn't have a way to return the corrected map.

A hack in eg show_preds - but this is very wrong!
for pred in preds: 
    pred['labels']=pred['labels']+1

**Comment by lgvaz** [comment]
A way of handling this is to do the conversion back in the `predict` method we implement for mmdet models.

what do you think?

**Comment by adamfarquhar** [comment]
I'm unsure of this. There is an architectural issue here about how the responsibility of the adaptors and what they apply to. 

The parser hacks the class map and adds the background to '0' or 'k' as appropriate. If it adds it at 'k', then it also renumbers other classes (e.g. '1' becomes '0'). If it hacked the ground truth, shouldn't everything work out? I.e., I'm not sure why anyone should see a '1' as the first class.

> A way of handling this is to do the conversion back in the `predict` method we implement for mmdet models.
> 
> what do you think?
