### ISSUE TITLE
Google colab dependency conflicts

### ISSUE THREAD

**Issue by ieriii** [airctic/icevision#662]
## 🐛 Bug
**Describe the bug**
Hi. I noted today I cannot install the icevision library in google colab anymore.

**To Reproduce**
!pip install icevision[all] 
!pip install icedata 

**Error**
```
ERROR: torchtext 0.9.0 has requirement torch==1.8.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.25.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
ERROR: omegaconf 2.0.6 has requirement PyYAML>=5.1.*, but you'll have pyyaml 3.13 which is incompatible.
ERROR: pytorch-lightning 1.2.2 has requirement PyYAML!=5.4.*,>=5.1, but you'll have pyyaml 3.13 which is incompatible.
```

**Comment by Algo-Dev** [comment]
Thanks for the post. To help others find this solution I Just want to mention that without your fix importing IceVision results in the following error:
in pytorch_lightning/utilities/apply_func.py", line 28,
from torchtext.data import Batch
ImportError: cannot import name 'Batch' from 'torchtext.data' (/home/daniel/py38/lib/python3.8/site-packages/torchtext/data/init.py)

**Comment by Algo-Dev** [comment]
Lightning have it updated in their Gitub version, but they haven't updated the pip version, installing their latest version from Github also solves the problem. So yes, they still have a problem with the pip version.

**Comment by lgvaz** [comment]
Should be working now, I just merged a quick fix with #685

**Comment by robmarkcole** [comment]
Just installed form master into colab, getting error:

```
----> 1 from icevision.all import *
      2 
      3 import icevision
      4 icevision.__version__

4 frames
/usr/local/lib/python3.7/dist-packages/icedata/datasets/birds/parser.py in <module>()
     13 class BirdsParser(
     14     parsers.Parser,
---> 15     parsers.FilepathMixin,
     16     parsers.MasksMixin,
     17     parsers.BBoxesMixin,

AttributeError: module 'icevision.parsers' has no attribute 'FilepathMixin'
```

**Comment by lgvaz** [comment]
@robmarkcole How did you install `icedata`? probably you're using the pypi version, but you also need it from master

**Comment by robmarkcole** [comment]
@lgvaz currently getting issues on colab even from master using 
```
!pip install git+git://github.com/airctic/icedata.git@master
!pip install git+git://github.com/airctic/icevision.git@master
```

**Comment by lgvaz** [comment]
@robmarkcole Thanks for the update, I recently broke it [this](https://github.com/airctic/icevision/commit/2873681403e762946c531b6b425cde54f7eff80e#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52)  commit.

It's fixed now

**Comment by FraPochetti** [comment]
We are currently fixing all the installation processes.
