### ISSUE TITLE
ClassMap with non-sequential IDs

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#668]
How to handle non-sequential IDs? Example:

```python
{1: bike, 2: car, 5: motorcycle}
```

### Suggestion 1
The user can only pass a list of labels to the `ClassMap`, it's the job of the user to fill the missing information:
```
[bike, car, None, None, motorcycle]
```

We only need to modify the coco parser for this (so it returns 90 classes instead of 80). Torchvision models and efficientdet expects coco to have 90 classes.

### Suggestion 2
Enable to receive a dict on the `ClassMap` constructor and automatically fill the missing blanks. Checks needs to be implement to make sure the keys of the dict are ints.

**Comment by potipot** [comment]
I'd opt for the Suggestion 1: what you see is what you get (+background :D)
