### ISSUE TITLE
Rename ImageID to ItemID

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#669]
ImageID might not be general enough, we might be working with audio files or text in the future.

@rsomani95 you suggested `ItemID` in the forums right? Or was it something else?

**Comment by rsomani95** [comment]
That's right, `ItemID` is what I'd suggested. `SampleID` or `RecordID` also work. `RecordID` would be the most consistent with the philosophy of what a `Record` is. What do you think?

**Comment by lgvaz** [comment]
Yeah, `RecordID` makes A LOT of sense! hahahaha
