### ISSUE TITLE
Fix plot_top_losses

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#674]
`plot_top_losses` got broken because of the new refactor, the type of the data passed to it now changed, we just need to make the tests pass.

What were `samples` before is not just `Record`s and don't have a `dict` like interface anymore.

@FraPochetti would you be interested in this one?

**Comment by FraPochetti** [comment]
Sure, but not immediately. I think it might take a couple of months or so, given I am on yolov5 now.

**Comment by lgvaz** [comment]
> Sure, but not immediately. I think it might take a couple of months or so, given I am on yolov5 now.

Okay, no problem!!

**Comment by FraPochetti** [comment]
@lgvaz 
Those "couple of months" that I mention are completely indicative btw :D (just wanted to be conservative with yolo).
I really hope to be done sooner than that! and in any case, this fix should not take much time so I might just slide it somewhere when I have a couple of free hours ;)
Is this just the tests that are broken or the entire functionality?

**Comment by lgvaz** [comment]
> Is this just the tests that are broken or the entire functionality?

What broke is that before `sample` was a dict and now it's a `Record`, so getting attributes with  `["labels"]` and calling `.update` doesn't work anymore

But don't worry, it should be an straight forward fix on my side, I'll take a look

**Comment by FraPochetti** [comment]
I prefer doing that actually 😉. It will be the occasion to check out the new API.
I will take a look and keep you posted!

**Comment by FraPochetti** [comment]
I have made up my mind and decided to look into this one tonight 😁. I think it is important to have all tests passing ASAP. Yolo can wait another couple of days.
Coming back from a weekend out of town. Will check this out as soon as I step at home 😉

**Comment by FraPochetti** [comment]
Tests are actually ok.
The functionality is broken because of the `update` ([here](https://github.com/airctic/icevision/blob/b779b170997900ca2f948a064f346ef7f292a890/icevision/models/interpretation.py#L146)) as you mentioned.
