### ISSUE TITLE
Deprecate record `as_dict`

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#675]
`BaseRecord.as_dict` was only a temporary solution and I believe it's not used anywhere anymore. We should double check that and remove `as_dict` from `BaseRecord` and all `RecordComponent`s.

### How-to
In `icevision/core/record_components.py` you can find the function `as_dict` in multiple places. Remove it from all components and make sure all tests are passing.

**Comment by FraPochetti** [comment]
Not enough bandwidth.
