### ISSUE TITLE
fasterrcnn does not work with forward hooks (including wandb)

### ISSUE THREAD

**Issue by adamfarquhar** [airctic/icevision#676]
It appears that faster-rcnn does not work properly with fastai (2.1.4) and WandB. This appears to be a bug in WandB.

I have a model that trains without WandB. When I add the WandB callback, it crashes. Identifying the precise point is not easy. In the same environment, efficientdet works with fastai and the WandB callback.
```python
Traceback (most recent call last):
  File "/home/adam/anaconda3/envs/dlm/lib/python3.8/site-packages/fastai/learner.py", line 155, in _with_events
    try:       self(f'before_{event_type}')       ;f()
  File "/home/adam/anaconda3/envs/dlm/lib/python3.8/site-packages/fastai/learner.py", line 164, in _do_one_batch
    self.pred = self.model(*self.xb)
  File "/home/adam/anaconda3/envs/dlm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/adam/anaconda3/envs/dlm/lib/python3.8/site-packages/torchvision/models/detection/generalized_rcnn.py", line 80, in forward
    images, targets = self.transform(images, targets)
  File "/home/adam/anaconda3/envs/dlm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 740, in _call_impl
    var = var[0]
TypeError: 'ImageList' object is not subscriptable
```
This error occurs in wandb_torch.py in `nested_shape` (line 20). It iterates `for item in list(array_or_tuple)` but the value of `array_or_tuple` is a `torchvision.models.detection.image_list.ImageList` object. This has two attributes: image_sizes (for a batch size of 8, this could be a list of tuples (512, 512) *8; and tensors, which is actually a single tensor, this could be a tensor of shape (8,3,512,512). So the imagelist is not sub-scriptable and the test fails.

**Comment by adamfarquhar** [comment]
bug in wandb_torch / pytorch / detection
The problem occurs in pytorch module.py and is triggered by the WandB forward hook.

- If wandb is not added, then there is no forward hook and the problem in module.py is not triggered
- If wandb is added, then there is a forward hook. The output of the fasterrcnn module is a tuple (ImageList, dict). The code in 
  module.py expects to be able to keep going down the left-most piece of output until it finds a tensor (see `var=var[0]` below). But this doesn't work with the ImageList object. Hence the 'ImageList' object is not subscriptable exception.

- I'm not really sure if the bug here is in pytorch module, pytorch detection, or wandb. I think that ImageList is probably not respecting the contract (implicit) of the pytorch module code.
- I previously thought that the problem was with wandb nested_shape, which basically makes the same assumption as pytorch module. In fact, the output of nested_shape does not appear to be used directly in the code other than being stashed in a node object under the output_shape attribute.

```python
          for hook in itertools.chain(
                _global_forward_hooks.values(),
                self._forward_hooks.values()):
            hook_result = hook(self, input, result)
            if hook_result is not None:
                result = hook_result
        if (len(self._backward_hooks) > 0) or (len(_global_backward_hooks) > 0):
            var = result
            while not isinstance(var, torch.Tensor):
                if isinstance(var, dict):
                    var = next((v for v in var.values() if isinstance(v, torch.Tensor)))
                else:
                    var = var[0]
```

**Comment by adamfarquhar** [comment]
To use WandB with FasterRCNN, you can call `wandb.init` with `log_parameters=False` and `log_gradients=False` . These two loggers are implemented with a forward hook that triggers the bug above.

**Comment by lgvaz** [comment]
@FraPochetti didn't we faced this issue (or a very similar one) before?

**Comment by adamfarquhar** [comment]
Thanks for pointing out that this is basically a duplicate of #527 and #490 

One minor improvement to the current patch would be to catch the wandbcallback in calls to instantiate Model and Learn.

**Comment by lgvaz** [comment]
> One minor improvement to the current patch would be to catch the wandbcallback in calls to instantiate Model and Learn.

We're currently catching it on the `Learn` instantiation, what you have in mind for catching while instantiating the model?

**Comment by FraPochetti** [comment]
Won't fix.
