### ISSUE TITLE
Update tutorials for 0.7.0 API

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#691]
There are actually two issues to be addressed here:

1. Updating the tutorials to the newest API
2. Restructuring the organization of the tutorials 
3. Make sure all tutorials are working as expected (model training, records parsed, etc)

The first issue is straight forward and we can use [this](https://github.com/airctic/icevision/blob/master/docs/transition.md) document as a reference on what needs to be updated. 

The second issue requires more thought and discussion. The main current problem is that we have a lot of repetition between our tutorials and this makes it very hard to maintain and update whenever we change something. We need a structure that reduces duplication while still showcasing all our features (and specially the support for multiple models).

### Suggestion 1

![image](https://user-images.githubusercontent.com/16520544/111316026-ac800780-8641-11eb-9014-d1028fc7f7f0.png)

The notebooks under training are minimal (almost without any text) and just showcase how to train a particular model. [Here](https://github.com/airctic/icevision/blob/master/notebooks/training_efficientdet.ipynb) is an example of a minimal notebook.

**Comment by lgvaz** [comment]
Once this is done we can open issues for each individual tutorial

**Comment by mayankjainllrl** [comment]
Hey, I am python developer thinking of getting started with open source works. I am new to open source world haven't contributed anything. Thought I could get started by working on this issue under your mentorship and guidance.

**Comment by lgvaz** [comment]
@mayankjainllrl hi hi! Thanks for reaching out! Please join our discord forum so we can communicate better =)
https://discord.gg/JDBeZYK

**Comment by spiyer99** [comment]
@lgvaz I've updated the negative_samples tutorial as per the transition doc. 
https://github.com/spiyer99/icevision/blob/master/notebooks/negative_samples.ipynb

 Am I on the right track here? It seems like most of the other tutorials have already been updated.

**Comment by FraPochetti** [comment]
Working on it.
