### ISSUE TITLE
Transforms only work for a single task

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#693]
## 🐛 Bug
Currently the transforms (`tfms.A.Adapter`) are hard-coded to work on a single task (mainly `detection`). The current API offers the capability of a more general approach where multiple tasks can be handled, right now this is basically a task on figuring out what is the best way of using albumentations for this.

**Comment by rsomani95** [comment]
@lgvaz we briefly discussed this on a call, but perhaps it's worth considering moving to a more functional approach for albumentation transforms?

The two main issues with the current adapter are:
1. hard-coded
2. it will try to call `setup_transform` on _each_ component. This may be highly undesirable as you could have multiple `ImageRecordComponents` but only want the transforms to be applied to a specific one of them

**Comment by lgvaz** [comment]
@rsomani95 the problems is that it's hard to make assumptions here right?

For example, the second point, maybe we do want to call transforms for each of the `ImageRecordComponent`, maybe each one of them have a different image?

**Comment by rsomani95** [comment]
@lgvaz for sure, that's a very valid use case. What I'm saying is we should _have the option_ to do either of those (with applying it to all components being the default perhaps)

**Comment by FraPochetti** [comment]
Not enough bandwidth to implement this.
