### ISSUE TITLE
Improve inference/prediction workflow

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#694]
## 🚀 Feature
Currently calling `predict` will return the predictions only based on the transformed image, i.e. if your image was resized, the bboxes coordinates will be returned based on the resized coordinates.

But the input record passed to `predict` should contain all necessary information (maybe not padding) so we can transform the prediction back to the original input.

**Comment by lgvaz** [comment]
related to #690

**Comment by rsomani95** [comment]
@lgvaz Is there a minimal reproducable example to start playing with this. Precisely, I mean an example where I can have a pre and post-transformation record object.

In theory, the simplest solution I can think of will require _only_ the original height and width as additional info. We can normalize the required bbox/kps/mask coordinates and scale it back to the original size. This is how Label Studio works behind the scenes, and I _think_ it's what albumentations does internally also

**Comment by lgvaz** [comment]
@rsomani95 I don't have a minimal example right now, but you can check that you record has the field `original_img_size` that will not get modified after transforms are applied, the idea is to use that info inside `predict`

**Comment by FraPochetti** [comment]
This is taken care of within the `end2end_detect` function.
