### ISSUE TITLE
Update default parsers with `is_new`

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#706]
Make use of the recent implemented parameter `is_new` that is passed to `Parser.parse_fields`

Functions like `record.set_filepath`, `record.set_img_size`, now only need to be called once, refer to [this](https://github.com/airctic/icevision/blob/master/notebooks/custom_parser.ipynb) notebook for an example.

We need to update or default parsers to make use of this functionality: 
- [ ] `coco_parser.py`
- [ ] `voc_parser.py`
- [ ] `via_parser.py`

**Comment by aaodiall** [comment]
I will look this on the week end.

**Comment by lgvaz** [comment]
@aaodiall Thanks a lot! I just assigned the issue to you
