### ISSUE TITLE
Improve visualization

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#710]
Improvements:
* Meme like border around text
* Classif labels on top-left or bottom-left
* New line for multiple labels in classif
* padding for labels from bbox edge

@rsomani95 Interested in this one? :sweat_smile:

**Comment by rsomani95** [comment]
Sure. You can assign this to me

**Comment by rsomani95** [comment]
Also, dynamic padding for labels from bbox edge

**Comment by lgvaz** [comment]
> Also, dynamic padding for labels from bbox edge

I edit the the list and added this

**Comment by lgvaz** [comment]
closed with #713
