### ISSUE TITLE
Standardize backbone argument in model method

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#727]
## 🐛 Bug
**Describe the bug**
When creating a torchvision model, it fails because `backbone` argument is passed as function, and `model()` method expects an nn.Module. The `backbone` method need to be called before it is passed to the `model()` method

**Comment by lgvaz** [comment]
Another suggestion:

Make all backbones callable, i.e. instead of `models.mmdet.retinanet.backbone.resnet18` directly returning a `MMDetBackboneConfig` it can instead return a function that when called returns a backbone config. Same applies for effdet
