### ISSUE TITLE
Update to torch 1.8

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#739]
mmcv just released support for torch 1.8, all other dependencies are ready, we're ready to update

- [ ] update setup.cfg
- [ ] fix potential breaking changes

**Comment by adamfarquhar** [comment]
I've been working on this. It is an important change, as 1.8 offers better compatibility with cuda 11.1 and Ampere GPUs (including RTX 30 Series).

I would suggest using torch<1.9. There do not seem to be any breaking changes in 1.8.1 that I've come across.

To build a docker image, it is essential for MMCV to know about the target GPUs. This is communicated with the following environment variables.
```
FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel
ARG FORCE_CUDA="1"
ARG MMCV_WITH_OPS=1
ARG CUDA_HOME="/usr/local/cuda"

# For all of the cuda archs:
# ARG TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX"

ARG TORCH_CUDA_ARCH_LIST="7.5 8.0 8.6+PTX"

WORKDIR /workspace
RUN apt-get update && apt-get install -y --no-install-recommends git build-essential gcc vim && \
    rm -rf /var/lib/apt/lists/

# We get a conflict unless we pin pyyaml
RUN pip install --no-cache-dir pyyaml==5.3

RUN pip install --no-cache-dir mmcv-full==1.3 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.1/index.html
RUN pip install --no-cache-dir mmdet

RUN pip install -e git+https://github.com/rwightman/efficientdet-pytorch#egg=effdet

RUN pip install --no-cache-dir ipywidgets jupyterlab
RUN pip install --no-cache-dir fastapi "flake8 >=3.8.3,<4" pytest "pre-commit >=2.8.2,<3"

# NOTE FORK! Replace when icevision is  updated
RUN pip install -e git+https://github.com/adamfarquhar/icevision.git#egg=icevision[all]
RUN pip install --no-cache-dir git+git://github.com/airctic/icedata.git

```

**Comment by adamfarquhar** [comment]
The only problems that I've seen are related to icevision 0.7, not torch 1.8.1.

**Comment by lgvaz** [comment]
I see that on your fork you updated pytorch-lightning version, do we also need to update fastai?

**Comment by adamfarquhar** [comment]
I've not tried this yet.  I wanted to check with you and others if there are any expected problems.  Why  was 2.1.4 was pinned?

**Comment by lgvaz** [comment]
If I recall correctly it's because of this:
![image](https://user-images.githubusercontent.com/16520544/114551524-e8ef5500-9c39-11eb-9338-b19c177be175.png)

**Comment by lgvaz** [comment]
aaah, we can't update yet, fastai is still on 1.7: https://github.com/fastai/fastai/blob/master/settings.ini#L17

**Comment by weiji14** [comment]
> aaah, we can't update yet, fastai is still on 1.7: https://github.com/fastai/fastai/blob/master/settings.ini#L17

There is support for Pytorch 1.9 for fastai > v2.4, is it possible to relax icevision's pytorch pinning to allow Pytorch 1.9 to be installed? I.e. change this line:

https://github.com/airctic/icevision/blob/b6c750f2ca5acfafd0e46e172a817af7a6892f18/setup.cfg#L28

Crossreferencing downstream issue https://github.com/PyTorchLightning/lightning-flash/issues/711, where pytorch 1.8.1 is being installed due to icevision's pytorch pin.

**Comment by lgvaz** [comment]
I'm not sure icevision is currently fully compatible with 1.8; @weiji14 are you able to run all tutorial notebooks and tests  after the update? If so, feel free to open a PR

**Comment by weiji14** [comment]
> I'm not sure icevision is currently fully compatible with 1.8; @weiji14 are you able to run all tutorial notebooks and tests after the update? If so, feel free to open a PR

Ok, I thought the CI was using pytorch 1.8, but will try out a few things locally and see how it goes. Will open a PR tomorrow.

**Comment by dlangerm** [comment]
I would also love to be able to install lightning-flash correctly without conda downgrading my torch install. 

BTW this strict dependency also causes torch to be downgraded to the CPU version even if the GPU version is installed when I install or update lightning-flash[image]. 😢

**Comment by Usama3059** [comment]
ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol:   getting this error while running the object detection notebook it is related with PL, also I tried some solutions for this, but got torchvision nms error please suggest me any solution to install icevision?

**Comment by FraPochetti** [comment]
This is done.
