### ISSUE TITLE
Use class_map on inference workflow

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#776]
## 🚀 Feature
Currently there is no default way to set `ClassMap` in the inference workflow. Specially because we end up creating the inference dataset like so:
```python
infer_ds = Dataset.from_images([img], infer_tfms)
```
There is no place to pass the class_map here. It's not so easy as to add a parameter `class_map` to this function because we don't know the task is should be set on (in the majority of cases it will be under `.detection` but we cannot be sure).

**Comment by KangolHsu** [comment]
add class_map like this：
infer_ds = Dataset.from_images([img], infer_tfms, class_map=class_map)

version0.8.0 works fine。

**Comment by FraPochetti** [comment]
Resolved.
