### ISSUE TITLE
draw_bbox fails for grayscale images

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#806]
## 🐛 Bug
`draw_data` contains the line: `img = PIL.Image.fromarray(img)`. If the image is grayscale and in the format `(h,w,1)` (which is what icevision expects` it fails with the error:
```python
TypeError: Cannot handle this data type: (1, 1, 1), |u1
```

---
**More info:**
https://stackoverflow.com/questions/63367136/pil-typeerror-cannot-handle-this-data-type-1-1-1-u1

**Comment by lgvaz** [comment]
It seems `draw_masks` and `draw_keypoints` also use this logic, so they will all fail

**Comment by FraPochetti** [comment]
Not relevant anymore.
