### ISSUE TITLE
Inference detection threshold

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#818]
Currently we pass `detection_threshold` to `model_type.predict`, it works but if I want to test multiple threshold values I have to run prediction all over again, which is very inefficient.

We need to figure out a way of applying the threshold after the predictions are done, maybe something like `pred.apply_threshold(0.2)` or something like that?

**Comment by fabiogeraci** [comment]
any progress on this

**Comment by lgvaz** [comment]
Not yet, we're currently looking on someone to implement this

**Comment by FraPochetti** [comment]
Not enough bandwidth to implement.
