### ISSUE TITLE
Single Task Within Record Can Accept Multiple Components Of The Same Type

### ISSUE THREAD

**Issue by rsomani95** [airctic/icevision#825]
## 🐛 Bug
Currently, you can add the same type of component multiple times to a task component. This could lead to unexpected and very difficult to track bugs down the line. Take this for example:
```python
rec = BaseRecord([FilepathRecordComponent()])
rec

# Output:
BaseRecord

common: 
	- Image ID: None
	- Filepath: None
	- Image: None
	- Image size None
```

Now, if I do this:
```python
rec.add_component(BBoxesRecordComponent())
rec.add_component(BBoxesRecordComponent())
rec.add_component(BBoxesRecordComponent())
rec

# Output:
BaseRecord

common: 
	- Filepath: None
	- Image: None
	- Image ID: None
	- Image size None
detection: 
	- BBoxes: []
	- BBoxes: []
	- BBoxes: []
```

Clearly, three separate components for bboxes have been added:
```bash
rec.detection.components

# Output
[<icevision.core.record_components.BBoxesRecordComponent at 0x7ffc9082a490>,
 <icevision.core.record_components.BBoxesRecordComponent at 0x7ffc9082a350>,
 <icevision.core.record_components.BBoxesRecordComponent at 0x7ffc9082a950>]
```

If I call `record.detection.set_boxes`, it only applies to the first component at `0x7ffc9082a490`

---

I think it should be made illegal to add multiple components of the same type to a single `Task`. Does that make sense?

**Comment by lgvaz** [comment]
> I think it should be made illegal to add multiple components of the same type to a single Task. Does that make sense?

Makes total sense, in the first iterations of the API we had were using a `set` to take care of that - but that when we were just passing classes to `BaseRecord` and not concrete objects

It's not quite clear how we should check for unique components now, if you use `isinstance(component, BBoxesRecordComponent)` you will have problems with subclasses (if you have a subclass of `BBoxes...` this will not allow you to add it). Maybe we can direct check for the class type?

Idk, open to suggestions

**Comment by FraPochetti** [comment]
Not enough bandwidth to implement.
