### ISSUE TITLE
Upgrade `fastai` compatibility

### ISSUE THREAD

**Issue by rsomani95** [airctic/icevision#829]
Currently, we're pinned to <= 2.1.5 of `fastai`. There's been several improvements since then, most notably a change in the mechanism that callbacks are called, and better native support for fp-16 training. 

It'd be nice to upgrade, and may solve a bunch of the existing fastai related issues as well

**Comment by potipot** [comment]
pinning to fastai=>2.2.2 would allow multi-gpu training as I have demonstrated in my presentation

**Comment by lgvaz** [comment]
done with 0.8! =)
