### ISSUE TITLE
Interactive visualization of data

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#83]
## 🚀 Feature

We need an interactive way to visualize data, we can interactively visualize bounding boxes and masks with wandb like described [here](https://www.wandb.com/articles/bounding-boxes).

We can also use streamlit, I'm not sure which is cooler.

Wandb draws more my attention because we can also use it for visualizing training statics (in real time), something that would be very very helpful, is to show the predictions of the model after every epoch.

This would provide strong insight on what the model is correctly learning and what it's fail to learn,  I believe a tool like this quickly becomes invaluable for anyone training models (it actually surprises me that this simple feature is not widespread at this point)

**Comment by lgvaz** [comment]
@paras-jain is this something you would like to work on?

**Comment by paras-jain** [comment]
Yes sure! streamlit makes deployment very easy and wandb helps in tracking and optimization, we should not miss out on either. I will look into it and then work on #84.
Has any [previous](https://github.com/lgvaz/mantisshrimp/issues/39#issuecomment-636639684) work been done?

**Comment by lgvaz** [comment]
Not really, we talked about it multiple times, but never found the time to implement it 😅

**Comment by oke-aditya** [comment]
> 
> 
> Yes sure! streamlit makes deployment very easy and wandb helps in tracking and optimization, we should not miss out on either. I will look into it and then work on #84.
> Has any [previous](https://github.com/lgvaz/mantisshrimp/issues/39#issuecomment-636639684) work been done?

Something to get strated
https://github.com/streamlit/demo-self-driving

**Comment by FraPochetti** [comment]
Taken care of by @fstroth 's dashboard
