### ISSUE TITLE
EXIF tag image rotation and get_image_size

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#838]
Conversation had on the forum: https://discord.com/channels/735877944085446747/735877944517591151/839134323428950067

Right now we implemented a quick fix to use PIL to read the image size, but that's very slow compared to the previous solution.

Previous:
![image](https://user-images.githubusercontent.com/16520544/117155330-10e25c00-ad93-11eb-9e79-a22f21aaa0de.png)

Current:
![image](https://user-images.githubusercontent.com/16520544/117155230-fb6d3200-ad92-11eb-9078-1a0bab79330b.png)

**Comment by FraPochetti** [comment]
Reolved.
