### ISSUE TITLE
Wandb sweeps tutorial

### ISSUE THREAD

**Issue by lgvaz** [airctic/icevision#84]
## 📓 New <Tutorial/Example>
**Is this a request for a tutorial or for an example?**  
Tutorial.

We need a tutorial on how to use wandb sweeps, after we understand how to properly use it we can even add a helper function in the core library if it seems fitting.

---
**Don't remove**
Main issue for examples: #39

**Comment by lgvaz** [comment]
@paras-jain this also has wandb that I know interests you, this is why I'm tagging 😁, pick the task you would most like to work in

**Comment by oke-aditya** [comment]
Please have look at [this](https://github.com/oke-aditya/mantisshrimp_wandb). @ai-fast-track @lgvaz @paras-jain .
Let me know what improvements are needed. It is silightly complex to set up and do the job. Also, we need to make .py files as wandb does not support jupyter very well. So how does that go in our docs ?

**Comment by FraPochetti** [comment]
Not relevant for the time being.
