### ISSUE TITLE
`PIL.Image` <=> `np.ndarray` uniformity

### ISSUE THREAD

**Issue by rsomani95** [airctic/icevision#852]
Currently, we're always returning a `np.ndarray` from the `Dataset`.
The `ImageRecordComponent` returns a `PIL.Image` by default and the albu adapter converts it internally to a `np.ndarray.` When not using these transforms, we force convert it to `np.ndarray`:
https://github.com/airctic/icevision/blob/cb602f533c7e114280904e70eed6c1069931c13a/icevision/data/dataset.py#L39-L40

It'd be nice to arrive at a more uniform, consistent way of handling this

**Comment by FraPochetti** [comment]
Not enough bandwidth to handle this.
