### ISSUE TITLE
Pass show_preds(**draw_sample_kwargs) also to annotations

### ISSUE THREAD

**Issue by maivels** [airctic/icevision#858]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**
`show_preds()` draw_sample_kwargs only get passed to preds but not annotations

**Describe the solution you'd like**
Pass **draw_sample_kwargs also to preds

**Context**
I cannot change the font_size of annotation bbox labels.

**Comment by lgvaz** [comment]
Thanks for opening the request @maivels! Is there a simple solution you have in mind?

**Comment by FraPochetti** [comment]
This should be fixed.
