### ISSUE TITLE
Colab 'fridge' example won't run

### ISSUE THREAD

**Issue by coldfir3** [airctic/icevision#862]
When trying to run the colab example https://colab.research.google.com/github/airctic/icevision/blob/master/notebooks/getting_started_object_detection.ipynb the notebook fails when installing dependencies making impossible to load icevision module.

I didn't changed any of the code and just ran the notebook, looking forward to a working example so I can try this interesting module =)

**Comment by lgvaz** [comment]
This is being fixed with #864 =)

**Comment by vpeopleonatank** [comment]
Although dependency error is shown, I can still use parser, training model and inference.

**Comment by FraPochetti** [comment]
Resolved.
