### ISSUE TITLE
conda env export results in error InvalidVersionSpec: Invalid version '2.0.2<3': invalid character(s)

### ISSUE THREAD

**Issue by tfriedel** [airctic/icevision#871]
## 🐛 Bug
**Describe the bug**
in a conda environement with icevision 0.8 I run 
"conda env export" to export the environment file.

I see this error:

InvalidVersionSpec: Invalid version '2.0.2<3': invalid character(s)

**To Reproduce**
install fresh icevision, icedata etc in new conda env according to the instructions.
Activate environment and run
conda env export

**Expected behavior**
YAML file output for the conda environement.

I tracked down the error to the line
27:Requires-Dist: pycocotools (>=2.0.2<3)
in 
lib/python3.8/site-packages/icevision-0.8.0.dist-info/METADATA

which can be traced back to 
pycocotools>=2.0.2<3
in icevision/setup.cfg

I think it can be fixed by writing it with a comma like so:
pycocotools<3,>=2.0.2

There's more lines like this that also need fixing.

**Comment by lgvaz** [comment]
That makes sense! Would you like to open a PR with the proposed fixes?

**Comment by dlangerm** [comment]
This is actually a pretty nasty bug affecting pytorch-lightning flash as well. Please fix soon.

**Comment by lgvaz** [comment]
@dlangerm tell me if it solved the issue =)
