### ISSUE TITLE
Bad links in Transforms / Albumentations README

### ISSUE THREAD

**Issue by drscotthawley** [airctic/icevision#876]
## 📓 Documentation Update
**What part of documentation was unclear or wrong?**
In https://github.com/airctic/icevision/blob/master/icevision/tfms/README.md
The hyperlink around "aug_tfms" 404's. 
Two example images near the bottom do not exist. 

**Describe the solution you'd like**
Proper links and images where they're supposed to be.  Where can I find more about "aug_tfms"? What are these images?   I was looking forward to learning more about the available transforms; currently this page doesn't tell me. 

**Additional context**
These errors are persisted on https://airctic.com/0.8.0/albumentations/

 Also note that the #feedback channel on Discord is set to read-only. Hard to give feedback there. :shrug:

**Comment by FraPochetti** [comment]
We are looking at all notebooks to make sure they all run smoothly.
