### ISSUE TITLE
"Join our Forum" button broken

### ISSUE THREAD

**Issue by vdefont** [airctic/icevision#884]
To repro:
1. Go to the homepage: https://airctic.com/0.8.0/
2. Click "Join our Forum"
3. Observe that the discord link is broken

The question I wanted to ask on the forum is: does icevision have a built-in way to do non-max suppression? Or is that something I'll have to implement myself?

**Comment by lgvaz** [comment]
Hi! The link seems to be working alright for me

And to answer your question, NMS already comes implemented with the majority of models; but it's not something icevision implements but the model libraries themselves

**Comment by FraPochetti** [comment]
Resolved.
