### ISSUE TITLE
Only getting a bounding box but no class label when inferencing an image

### ISSUE THREAD

**Issue by ethannakamura1211** [airctic/icevision#885]
I have trained an Object Detection model using RetinaNet. Is there a way currently, to display the bounding box and class name when an inference is run on a test image? The function I'm running is `show_preds(preds=preds)`, similar to this example: [https://github.com/airctic/icevision/blob/master/notebooks/inference.ipynb](url)

**Comment by FraPochetti** [comment]
You need to pass a `ClassMap` when creating the test dataset.
Take a look at the `end2end_detect` function.
