### ISSUE TITLE
Pillow Image class has no attribute shape

### ISSUE THREAD

**Issue by potipot** [airctic/icevision#889]
## 🐛 Bug
**Describe the bug**
Pillow Image class has no attribute shape. When using open_image function from utils/image_io.py the shape property is not defined for Pil Image class. 

This has been changed in 0.8.1 where we return PIL image instead of numpy array. To fix this one should try to access Image.height and Image.width fields instead or read these values from Image.size property.

**Expected behavior**
The show_records should be able to open the image without issues.

**Screenshots**
```python
show_records(records[:1])
```
![obraz](https://user-images.githubusercontent.com/52150545/125317783-8d685c80-e339-11eb-8e78-96c671729109.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
https://github.com/airctic/icevision/blob/d731a1c3d4a99c9bc9a887fd06c6fd82f0b1e76b/icevision/core/record_components.py#L118

**Comment by potipot** [comment]
this might be coming from the python poetry installation file. It is reproducible if icevision=0.8.1 is installed without specifying [all] egg

**Comment by jayqi** [comment]
Hi @ai-fast-track or other maintainers. We ran into this bug on the latest release (0.8.1). Can you please make a new release with this fix included?

**Comment by jpsimen** [comment]
+1 for a new release, please.

**Comment by Yacoub-Abulubad** [comment]
I am getting this similar bug but through a different approach, it's when I try to fit a tensorflow model I get thrown with this error 
![image](https://user-images.githubusercontent.com/70016369/147446006-45c4287f-8fe2-40ea-8690-c6c8afe93e19.png)

- OS: Windows 11
- Python: 3.8.12
- PIL: version 8.4.0
