### ISSUE TITLE
Add state of the art YOLOX model from YOLO series.

### ISSUE THREAD

**Issue by bogdan-evtushenko** [airctic/icevision#911]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**
The problem is basically in not sufficiency of mAP score for not big dataset size available.

**Describe the solution you'd like**
Adding model the newest version from YOLO series - YOLOX - to the list of available models to use ([github](https://github.com/Megvii-BaseDetection/YOLOX)) ([arxiv](https://arxiv.org/abs/2107.08430))

**Describe alternatives you've considered**
We did a couple of experiments and that's what we had:
- using YOLOv5 - the performance was worse (as it supposed to be).
- using EfficientDet has shown a little bit worse performance and training time as well (At least with our experiments).

**Comment by lgvaz** [comment]
@bogdan-evtushenko or @roboserg would you be up to adding this? It's a lot of work but should be straight forward, it should follow the same structure as our other models. If you're interested we can have a more detailed chat =)

**Comment by weiji14** [comment]
YOLOX is available in mmdetection (https://github.com/open-mmlab/mmdetection/tree/v2.16.0/configs/yolox), so might be easier to integrate into icevision at https://github.com/airctic/icevision/tree/master/icevision/models/mmdet/models :wink:

**Comment by bogdan-evtushenko** [comment]
> @bogdan-evtushenko or @roboserg would you be up to adding this? It's a lot of work but should be straight forward, it should follow the same structure as our other models. If you're interested we can have a more detailed chat =)

Yeap, I'm interested in adding that, let's have a chat?

**Comment by lgvaz** [comment]
@bogdan-evtushenko yeeep, are you in the discord server already?

**Comment by bogdan-evtushenko** [comment]
> @bogdan-evtushenko yeeep, are you in the discord server already?

Yes, Bohdan Yevtushenko#4938

**Comment by FraPochetti** [comment]
This is done.
