### ISSUE TITLE
Albumentations adapter overwrites image size when applying transforms

### ISSUE THREAD

**Issue by potipot** [airctic/icevision#920]
## 🐛 Bug
I'm working on custom inference loop and when converting the bboxes from the transformed image to the original one I noticed that the records original image size value gets overwritten. 

This happens when applying tfms in inference dataloader.

here we call `record.set_img` method 
```python
class AlbumentationsImgComponent(AlbumentationsAdapterComponent):
    def setup_img(self, record):
        # NOTE - assumed that `record.img` is a PIL.Image
        self.adapter._albu_in["image"] = np.array(record.img)

        self.adapter._collect_ops.append(CollectOp(self.collect))

    def collect(self, record):
+       record.set_img(self.adapter._albu_out["image"])
```

that will always overwrite the `img_size` as the original
```python
class ImageRecordComponent(RecordComponent):
    def __init__(self, task=tasks.common):
        super().__init__(task=task)
        self.img = None

    def set_img(self, img: Union[PIL.Image.Image, np.ndarray]):
        assert isinstance(img, (PIL.Image.Image, np.ndarray))
        self.img = img
        if isinstance(img, PIL.Image.Image):
            width, height = img.size
        elif isinstance(img, np.ndarray):
            # else:
            height, width, _ = self.img.shape
        # this should set on SizeRecordComponent
+       self.composite.set_img_size(ImgSize(width=width, height=height), original=True)
```

**Expected behavior**
Transforms that call `record.set_img` should not overwrite the original image size value.

**Comment by lgvaz** [comment]
Yeah, this was done on purpose I believe, so later stages of the pipeline can rely on `record.img_size` to actually match the image.

Can you further explain why this fails for your use case?

**Comment by potipot** [comment]
Okay, maybe I got a bit confused. What is then the difference and purpose of image size original and not original?

**Comment by FraPochetti** [comment]
@potipot is this still relevant?

**Comment by potipot** [comment]
I couldn't recreate that issue later. Closing.
