### ISSUE TITLE
Does yolov5-icevision support video streaming as like the original YOLOv5?

### ISSUE THREAD

**Issue by syenpark** [airctic/icevision#926]
Hello,
I wanna use LoadStreams in [YOLOv5/utils/datasets.py](https://github.com/ultralytics/yolov5/blob/master/utils/datasets.py) to handle video streaming, but I can't find any similar functions in yolov5-icevision. Doesn't yolov5-icevision support object detection for video streaming yet?

Thanks in advance.

**Comment by lgvaz** [comment]
We currently don't have helper functions for videos =/

I *think* it might be possible to still train your model using icevision and then using their `LoadStreams` as their instruct to run on videos (since we're basically training their models anyways)

**Comment by syenpark** [comment]
Thanks for informing me!
