### ISSUE TITLE
Inference - automatically recreate model trained with COCO

### ISSUE THREAD

**Issue by ai-fast-track** [airctic/icevision#928]
## 🚀 Feature

automatically recreate model trained with COCO if the user provide the model name, the backbone name, and the classes.

**Comment by FrancescoSaverioZuppichini** [comment]
You should allow the user to pass a configuration string to load the weights -> https://mmdetection.readthedocs.io/en/latest/tutorials/config.html

**Comment by FraPochetti** [comment]
This is done.
