### ISSUE TITLE
Breaking Change in 0.9.0a1: Rename of Class MasksRecordComponent Breaks PyTorch Lightning Flash

### ISSUE THREAD

**Issue by alexheat** [airctic/icevision#936]
## 🐛 Bug
**Describe the bug**
In 0.9.0a1 one of the classes is renamed. This change breaks PyTorch Lightning which calls the old class name. This is the PR where the change is made https://github.com/airctic/icevision/commit/83c1e862be7e2f51ea1018cbfea83747f80ad65c#diff-a0a78170020afb01b781114bf29dcc2f5f3773f5f863a03645f2b0f466540df7. The comment in the PR sums it up "renames MasksRecordComponent to InstanceMasksRecordComponent"

**To Reproduce**
I have created a notebook that repros the issue here https://gist.github.com/alexheat/c8fce52eb5e77aef9692cc087b63d447
The notebook installs release 0.9.0a1. 

 And then it terminates with this error "ImportError: cannot import name 'MasksRecordComponent' from 'icevision.core.record_components' (/usr/local/lib/python3.7/dist-packages/icevision/core/record_components.py)"

**Expected behavior**
Don't change the name or keep the old name for backwards compatibility.  

**Screenshots**
Error message "ImportError: cannot import name 'MasksRecordComponent' from 'icevision.core.record_components' (/usr/local/lib/python3.7/dist-packages/icevision/core/record_components.py)"

**Desktop (please complete the following information):**
 - Repo on google collab 

**Additional context**

**Comment by ethanwharris** [comment]
Fixed on Flash master so this issue could safely be closed :smiley:
