### ISSUE TITLE
Wrong version of mmcv installed in the doc

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [airctic/icevision#945]
## 📓 Documentation Update
**What part of documentation was unclear or wrong?**
In the doc you install version 1.3.3 of `mmcv` while it is incompatible with the hardcoded `mmdet` version `2.10.0` that you have in the code. Check here to see the supported versions https://mmdetection.readthedocs.io/en/v2.10.0/get_started.html

**Comment by FraPochetti** [comment]
We are working on getting the installation scripts right.
