### ISSUE TITLE
Get bounding boxes from Prediction

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [airctic/icevision#953]
Currently, it seems impossible to just get a list of bounding boxes from the predictions.

```python

img = np.array(Image.open("..."))
infer_ds = Dataset.from_images([img], valid_tfms, class_map=dm.parser.class_map)

preds = model_type.predict(model, infer_ds, keep_images=True)
# I just want the bounding boxes 
```

`preds` is a list of `Prediction` and the codebase is not easy to navigate in order to understand where are the actual predicitons. 

Thank you

**Comment by FraPochetti** [comment]
Bboxes can be extracted like this `preds[0].pred.detection.bboxes`
