### ISSUE TITLE
return matplotlib fig object from show_records and show_results instead of None

### ISSUE THREAD

**Issue by rbavery** [airctic/icevision#973]
This would allow us to use plt.savefig or manipulate the figure. plt.savefig works with `model_type.show_records` but not with `show_results` for some reason

for example,
this produces a saved empty image
```
x = model_type.show_results(model, valid_ds, detection_threshold=.7)
plt.savefig("inference_results.png")
```

**Comment by FraPochetti** [comment]
Adding `plt.savefig("filename.png")` works in no case for case, e.g. it always saves an empty image.
What is `model_type.show_records`?

**Comment by FraPochetti** [comment]
Closing
