### ISSUE TITLE
SSL Error when trying mmdet models

### ISSUE THREAD

**Issue by karthikra** [airctic/icevision#982]
## 🐛 Bug
**Describe the bug**
SSLError when trying to use the mmdet model
**To Reproduce**
1.model_type = models.mmdet.vfnet
2. backbone = model_type.backbones.resnet101_fpn_mstrain_2x
3. model = model_type.model(backbone=backbone(pretrained=True), num_classes=len(parser.class_map), **extra_args)
4. SSLError: HTTPSConnectionPool(host='openmmlab.oss-cn-hangzhou.aliyuncs.com', port=443): Max retries exceeded with url: /mmdetection/v2.0/vfnet/vfnet_r101_fpn_mstrain_2x_coco/vfnet_r101_fpn_mstrain_2x_coco_20201027pth-4a5d53f1.pth (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:1123)')))

**Expected behavior**
Instantiate the model
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. ubuntu 16.04]

**Additional context**

**Comment by FraPochetti** [comment]
This works on Colab.
Cannot reproduce.
