### ISSUE TITLE
Add detection_threshold arg for all Lightning adapters

### ISSUE THREAD

**Issue by Anjum48** [airctic/icevision#987]
## 🚀 Feature
**Is your feature request related to a problem? Please describe.**
At the moment, the detection threshold for inside `validation_step` is at or near zero for Lightning adapters. This results in pessimistic validation performance due to false positives.
https://github.com/airctic/icevision/blob/9abbb09f47e6fc18867a5aa662885b558af2975c/icevision/models/ross/efficientdet/lightning/model_adapter.py#L50
https://github.com/airctic/icevision/blob/9abbb09f47e6fc18867a5aa662885b558af2975c/icevision/models/ultralytics/yolov5/lightning/model_adapter.py#L51

**Describe the solution you'd like**
Add a kwarg in the init of the Lightning adapter

**Describe alternatives you've considered**

**Additional context**
Happy to submit a PR if you guys agree

**Comment by FraPochetti** [comment]
@potipot @fstroth @ai-fast-track wdyt?

**Comment by fstroth** [comment]
Sounds good to me, we should go forward with this.

**Comment by FraPochetti** [comment]
@Anjum48 would you like to submit a PR?
We'd love that!

**Comment by potipot** [comment]
Ah, this is actually the way it should be. When calculating COCOMetric (or mAP), we don't put the confidence threshold on detections but keep the best 100 of them for each image.

**Comment by FraPochetti** [comment]
Ah wait, so are you saying that we should keep the threshold to 0?
I think this doesn't change in the [PR](https://github.com/airctic/icevision/pull/1004), but can you take a look too?

**Comment by Anjum48** [comment]
Thanks for the clarification @potipot! I guess I was coming from the angle that a custom metric may need a confidence threshold, hence the need for this (in my case I implemented the F2 score from [this](https://www.kaggle.com/c/tensorflow-great-barrier-reef/overview/evaluation) ongoing competition.

I guess there might be some complexity in the future if you are using something like:
```
metrics = [COCOMetric(), F2Score()]
```
where `COCOMetric` does not require a threshold but `F2Score` does. In this particular case, would it be more sensible to put the threshold within the custom metric also?

**Comment by potipot** [comment]
yes exactly, I think it should be up to the metric to handle the predictions. 

For running inference [here](https://github.com/airctic/icevision/blob/4050e0eb0def68d964330b4861c79dd8ed5c7afe/icevision/models/ross/efficientdet/prediction.py#L43) we use the same underlying functions of `convert_raw_predictions` and we explicitly specify the `condifence_threshold` we want to use.

**Comment by Anjum48** [comment]
Ok @FraPochetti , @fstroth @ai-fast-track what do you guys think? I'm happy to close the PR as @potipot's suggestion makes a lot of sense

**Comment by FraPochetti** [comment]
I don't think there is a need to close the PR.
Your PR does not change the default metrics calculation behavior given the threshold is still set to 0.
You are just exposing the parameter which is a good thing for potential future use cases.
No?
As far as I am concerned we could merge it.

**Comment by FraPochetti** [comment]
> Ok @FraPochetti , @fstroth @ai-fast-track what do you guys think? I'm happy to close the PR as @potipot's suggestion makes a lot of sense

Hi @Anjum48, first of all, thanks again for all the effort here. We truly appreciate that.

We have been discussing internally and, eventually, we have come to the conclusion that @potipot's [idea](https://github.com/airctic/icevision/issues/987#issuecomment-997798965) makes the most sense.
Predictions, hence thresholds, are best handled at the metrics level.
Therefore, I am afraid we can't incorporate your PR into IceVision.
Would you mind closing it, please?

Once again, I hope you understand, and thanks for the exchange!
We hope you'll keep hanging out in our community and, most importantly, keep contributing!

**Comment by Anjum48** [comment]
No problems at all, I totally agree with you guys. Thanks for the great discourse - I learnt a lot! 😊

I'll go ahead and close the PR
